-- DO NOT EDIT - autogenerated by structgen
CREATE TABLE classrooms (
    id serial PRIMARY KEY,
    id_teacher integer NOT NULL,
    name varchar NOT NULL
);

CREATE TABLE teachers (
    id serial PRIMARY KEY,
    mail varchar NOT NULL,
    password_crypted bytea,
    is_admin boolean NOT NULL
);

ALTER TABLE classrooms
    ADD FOREIGN KEY (id_teacher) REFERENCES teachers ON DELETE CASCADE;

ALTER TABLE teachers
    ADD UNIQUE (mail);

