-- DO NOT EDIT - autogenerated by structgen
CREATE TABLE classrooms (
    id serial PRIMARY KEY,
    id_teacher integer NOT NULL,
    name varchar NOT NULL
);

CREATE TABLE students (
    Id serial PRIMARY KEY,
    Name varchar NOT NULL,
    Surname varchar NOT NULL,
    Birthday date NOT NULL,
    TrivialSuccess integer NOT NULL,
    IsClientAttached boolean NOT NULL,
    id_classroom integer NOT NULL
);

CREATE TABLE teachers (
    id serial PRIMARY KEY,
    mail varchar NOT NULL,
    password_crypted bytea,
    is_admin boolean NOT NULL
);

ALTER TABLE classrooms
    ADD FOREIGN KEY (id_teacher) REFERENCES teachers ON DELETE CASCADE;

ALTER TABLE students
    ADD FOREIGN KEY (id_classroom) REFERENCES classrooms ON DELETE CASCADE;

ALTER TABLE teachers
    ADD UNIQUE (mail);

