// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

// github.com/benoitkugler/maths-online/prof/homework.AddExerciceToTaskIn
export interface AddExerciceToTaskIn {
  IdSheet: IdSheet;
  IdExercice: IdExercice;
}
// github.com/benoitkugler/maths-online/prof/homework.AddMonoquestionToTaskIn
export interface AddMonoquestionToTaskIn {
  IdSheet: IdSheet;
  IdQuestion: IdQuestion;
}
// github.com/benoitkugler/maths-online/sql/reviews.Approval
export enum Approval {
  Neutral = 0,
  InFavor = 1,
  Opposed = 2,
}

export const ApprovalLabels: { [key in Approval]: string } = {
  [Approval.Neutral]: "",
  [Approval.InFavor]: "",
  [Approval.Opposed]: "",
};

// github.com/benoitkugler/maths-online/prof/teacher.AskInscriptionIn
export interface AskInscriptionIn {
  Mail: string;
  Password: string;
}
// github.com/benoitkugler/maths-online/prof/teacher.AskInscriptionOut
export interface AskInscriptionOut {
  Error: string;
  IsPasswordError: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions/client.Binary
export enum Binary {
  Invalid = 0,
  And = 1,
  Or = 2,
}

export const BinaryLabels: { [key in Binary]: string } = {
  [Binary.Invalid]: "Invalide",
  [Binary.And]: "Et",
  [Binary.Or]: "Ou",
};

export enum BlockKind {
  ExpressionFieldBlock = "ExpressionFieldBlock",
  FigureAffineLineFieldBlock = "FigureAffineLineFieldBlock",
  FigureBlock = "FigureBlock",
  FigurePointFieldBlock = "FigurePointFieldBlock",
  FigureVectorFieldBlock = "FigureVectorFieldBlock",
  FigureVectorPairFieldBlock = "FigureVectorPairFieldBlock",
  FormulaBlock = "FormulaBlock",
  FunctionPointsFieldBlock = "FunctionPointsFieldBlock",
  FunctionsGraphBlock = "FunctionsGraphBlock",
  NumberFieldBlock = "NumberFieldBlock",
  OrderedListFieldBlock = "OrderedListFieldBlock",
  ProofFieldBlock = "ProofFieldBlock",
  RadioFieldBlock = "RadioFieldBlock",
  SignTableBlock = "SignTableBlock",
  SignTableFieldBlock = "SignTableFieldBlock",
  TableBlock = "TableBlock",
  TableFieldBlock = "TableFieldBlock",
  TextBlock = "TextBlock",
  TreeFieldBlock = "TreeFieldBlock",
  VariationTableBlock = "VariationTableBlock",
  VariationTableFieldBlock = "VariationTableFieldBlock",
  VectorFieldBlock = "VectorFieldBlock",
}

// github.com/benoitkugler/maths-online/maths/questions.Block
export interface Block {
  Kind: BlockKind;
  Data:
    | ExpressionFieldBlock
    | FigureAffineLineFieldBlock
    | FigureBlock
    | FigurePointFieldBlock
    | FigureVectorFieldBlock
    | FigureVectorPairFieldBlock
    | FormulaBlock
    | FunctionPointsFieldBlock
    | FunctionsGraphBlock
    | NumberFieldBlock
    | OrderedListFieldBlock
    | ProofFieldBlock
    | RadioFieldBlock
    | SignTableBlock
    | SignTableFieldBlock
    | TableBlock
    | TableFieldBlock
    | TextBlock
    | TreeFieldBlock
    | VariationTableBlock
    | VariationTableFieldBlock
    | VectorFieldBlock;
}
// github.com/benoitkugler/maths-online/sql/trivial.CategoriesQuestions
export interface CategoriesQuestions {
  Tags: QuestionCriterion[];
  Difficulties: DifficultyQuery;
}
// github.com/benoitkugler/maths-online/prof/editor.CheckExerciceParametersIn
export interface CheckExerciceParametersIn {
  IdExercice: IdExercice;
  SharedParameters: Parameters;
  QuestionParameters: Parameters[] | null;
}
// github.com/benoitkugler/maths-online/prof/editor.CheckExerciceParametersOut
export interface CheckExerciceParametersOut {
  ErrDefinition: ErrParameters;
  QuestionIndex: number;
}
// github.com/benoitkugler/maths-online/prof/trivial.CheckMissingQuestionsOut
export interface CheckMissingQuestionsOut {
  Pattern: string[] | null;
  Missing: (string[] | null)[] | null;
}
// github.com/benoitkugler/maths-online/prof/editor.CheckQuestionParametersIn
export interface CheckQuestionParametersIn {
  SessionID: string;
  Parameters: Parameters;
}
// github.com/benoitkugler/maths-online/prof/editor.CheckQuestionParametersOut
export interface CheckQuestionParametersOut {
  ErrDefinition: ErrParameters;
  Variables: Variable[] | null;
}
// github.com/benoitkugler/maths-online/sql/teacher.Classroom
export interface Classroom {
  id: IdClassroom;
  id_teacher: IdTeacher;
  name: string;
}
// github.com/benoitkugler/maths-online/prof/teacher.ClassroomExt
export interface ClassroomExt {
  Classroom: Classroom;
  NbStudents: number;
}
// github.com/benoitkugler/maths-online/prof/homework.ClassroomSheets
export interface ClassroomSheets {
  Classroom: Classroom;
  Sheets: SheetExt[] | null;
}
// github.com/benoitkugler/maths-online/sql/reviews.Comment
export interface Comment {
  Time: Time;
  Message: string;
}
// github.com/benoitkugler/maths-online/sql/reviews.Comments
export type Comments = Comment[] | null;
// github.com/benoitkugler/maths-online/maths/questions.ComparisonLevel
export enum ComparisonLevel {
  AsLinearEquation = 102,
  ExpandedSubstitutions = 2,
  SimpleSubstitutions = 1,
  Strict = 0,
}

export const ComparisonLevelLabels: { [key in ComparisonLevel]: string } = {
  [ComparisonLevel.AsLinearEquation]: "",
  [ComparisonLevel.ExpandedSubstitutions]: "Complète",
  [ComparisonLevel.SimpleSubstitutions]: "Simple",
  [ComparisonLevel.Strict]: "Exacte",
};

// github.com/benoitkugler/maths-online/maths/repere.Coord
export interface Coord {
  X: number;
  Y: number;
}
// github.com/benoitkugler/maths-online/maths/questions.CoordExpression
export interface CoordExpression {
  X: string;
  Y: string;
}
// github.com/benoitkugler/maths-online/prof/homework.CopySheetIn
export interface CopySheetIn {
  IdSheet: IdSheet;
  IdClassroom: IdClassroom;
}
// github.com/benoitkugler/maths-online/prof/homework.CreateSheetIn
export interface CreateSheetIn {
  IdClassroom: IdClassroom;
}
// github.com/benoitkugler/maths-online/sql/teacher.Date
export type Date = Date_;
// github.com/benoitkugler/maths-online/prof/editor.DeleteExerciceOut
export interface DeleteExerciceOut {
  Deleted: boolean;
  BlockedBy: QuestionExerciceUses;
}
// github.com/benoitkugler/maths-online/prof/editor.DeleteQuestionOut
export interface DeleteQuestionOut {
  Deleted: boolean;
  BlockedBy: QuestionExerciceUses;
}
// github.com/benoitkugler/maths-online/sql/editor.DifficultyQuery
export type DifficultyQuery = DifficultyTag[] | null;
// github.com/benoitkugler/maths-online/sql/editor.DifficultyTag
export enum DifficultyTag {
  Diff1 = "★",
  Diff2 = "★★",
  Diff3 = "★★★",
  DiffEmpty = "",
}

export const DifficultyTagLabels: { [key in DifficultyTag]: string } = {
  [DifficultyTag.Diff1]: "1 étoile",
  [DifficultyTag.Diff2]: "2 étoiles",
  [DifficultyTag.Diff3]: "3 étoiles",
  [DifficultyTag.DiffEmpty]: "",
};

// github.com/benoitkugler/maths-online/maths/questions.Enonce
export type Enonce = Block[] | null;
// github.com/benoitkugler/maths-online/maths/questions.ErrParameters
export interface ErrParameters {
  Origin: string;
  Details: string;
}
// github.com/benoitkugler/maths-online/maths/questions.ErrQuestionInvalid
export interface ErrQuestionInvalid {
  ErrParameters: ErrParameters;
  ErrEnonce: errEnonce;
  ParametersInvalid: boolean;
}
// github.com/benoitkugler/maths-online/sql/editor.Exercice
export interface Exercice {
  Id: IdExercice;
  IdGroup: IdExercicegroup;
  Subtitle: string;
  Description: string;
  Parameters: Parameters;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceCreateQuestionIn
export interface ExerciceCreateQuestionIn {
  SessionID: string;
  IdExercice: IdExercice;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceDuplicateQuestionIn
export interface ExerciceDuplicateQuestionIn {
  QuestionIndex: number;
  IdExercice: IdExercice;
  SessionID: string;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceExt
export interface ExerciceExt {
  Exercice: Exercice;
  Questions: ExerciceQuestionExt[] | null;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceHeader
export interface ExerciceHeader {
  Id: IdExercice;
  Subtitle: string;
  Difficulty: DifficultyTag;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceImportQuestionIn
export interface ExerciceImportQuestionIn {
  IdQuestion: IdQuestion;
  IdExercice: IdExercice;
  SessionID: string;
}
// github.com/benoitkugler/maths-online/sql/editor.ExerciceQuestion
export interface ExerciceQuestion {
  id_exercice: IdExercice;
  id_question: IdQuestion;
  bareme: number;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceQuestionExt
export interface ExerciceQuestionExt {
  Question: Question;
  Bareme: number;
}
// github.com/benoitkugler/maths-online/sql/editor.ExerciceQuestions
export type ExerciceQuestions = ExerciceQuestion[] | null;
// github.com/benoitkugler/maths-online/prof/editor.ExerciceUpdateQuestionsIn
export interface ExerciceUpdateQuestionsIn {
  Questions: ExerciceQuestions;
  IdExercice: IdExercice;
  SessionID: string;
}
// github.com/benoitkugler/maths-online/prof/editor.ExerciceUpdateVisiblityIn
export interface ExerciceUpdateVisiblityIn {
  ID: IdExercicegroup;
  Public: boolean;
}
// github.com/benoitkugler/maths-online/sql/editor.Exercicegroup
export interface Exercicegroup {
  Id: IdExercicegroup;
  Title: string;
  Public: boolean;
  IdTeacher: IdTeacher;
}
// github.com/benoitkugler/maths-online/prof/editor.ExercicegroupExt
export interface ExercicegroupExt {
  Group: Exercicegroup;
  Origin: Origin;
  Tags: string[] | null;
  Variants: ExerciceHeader[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.ExpressionFieldBlock
export interface ExpressionFieldBlock {
  Expression: string;
  Label: Interpolated;
  ComparisonLevel: ComparisonLevel;
  ShowFractionHelp: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions.FigureAffineLineFieldBlock
export interface FigureAffineLineFieldBlock {
  Label: string;
  A: string;
  B: string;
  Figure: FigureBlock;
}
// github.com/benoitkugler/maths-online/maths/questions.FigureBlock
export interface FigureBlock {
  Drawings: RandomDrawings;
  Bounds: RepereBounds;
  ShowGrid: boolean;
  ShowOrigin: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions.FigurePointFieldBlock
export interface FigurePointFieldBlock {
  Answer: CoordExpression;
  Figure: FigureBlock;
}
// github.com/benoitkugler/maths-online/maths/questions.FigureVectorFieldBlock
export interface FigureVectorFieldBlock {
  Answer: CoordExpression;
  AnswerOrigin: CoordExpression;
  Figure: FigureBlock;
  MustHaveOrigin: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions.FigureVectorPairFieldBlock
export interface FigureVectorPairFieldBlock {
  Figure: FigureBlock;
  Criterion: VectorPairCriterion;
}
// github.com/benoitkugler/maths-online/maths/questions.FormulaBlock
export interface FormulaBlock {
  Parts: Interpolated;
}
// github.com/benoitkugler/maths-online/maths/questions.FunctionArea
export interface FunctionArea {
  Bottom: Interpolated;
  Top: Interpolated;
  Left: string;
  Right: string;
  Color: string;
}
// github.com/benoitkugler/maths-online/maths/functiongrapher.FunctionDecoration
export interface FunctionDecoration {
  Label: string;
  Color: string;
}
// github.com/benoitkugler/maths-online/maths/questions.FunctionDefinition
export interface FunctionDefinition {
  Function: string;
  Decoration: FunctionDecoration;
  Variable: Variable;
  From: string;
  To: string;
}
// github.com/benoitkugler/maths-online/maths/questions.FunctionPoint
export interface FunctionPoint {
  Function: Interpolated;
  X: string;
  Color: string;
  Legend: Interpolated;
}
// github.com/benoitkugler/maths-online/maths/questions.FunctionPointsFieldBlock
export interface FunctionPointsFieldBlock {
  Function: string;
  Label: string;
  Variable: Variable;
  XGrid: string[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.FunctionsGraphBlock
export interface FunctionsGraphBlock {
  FunctionExprs: FunctionDefinition[] | null;
  FunctionVariations: VariationTableBlock[] | null;
  Areas: FunctionArea[] | null;
  Points: FunctionPoint[] | null;
}
// github.com/benoitkugler/maths-online/prof/trivial.GamePlayers
export interface GamePlayers {
  Player: string;
  Successes: Success;
}
// github.com/benoitkugler/maths-online/prof/trivial.GameSummary
export interface GameSummary {
  GameID: RoomID;
  CurrentPlayer: string;
  Players: GamePlayers[] | null;
  RoomSize: number;
}
// github.com/benoitkugler/maths-online/prof/teacher.GenerateClassroomCodeOut
export interface GenerateClassroomCodeOut {
  Code: string;
}
// github.com/benoitkugler/maths-online/prof/homework.HomeworkMarksOut
export interface HomeworkMarksOut {
  Students: StudentHeader[] | null;
  Marks: { [key: IdSheet]: { [key: IdStudent]: number } | null } | null;
}
// github.com/benoitkugler/maths-online/prof/homework.HowemorkMarksIn
export interface HowemorkMarksIn {
  IdClassroom: IdClassroom;
  IdSheets: IdSheet[] | null;
}
// github.com/benoitkugler/maths-online/sql/teacher.IdClassroom
export type IdClassroom = number;
// github.com/benoitkugler/maths-online/sql/editor.IdExercice
export type IdExercice = number;
// github.com/benoitkugler/maths-online/sql/editor.IdExercicegroup
export type IdExercicegroup = number;
// github.com/benoitkugler/maths-online/sql/tasks.IdMonoquestion
export type IdMonoquestion = number;
// github.com/benoitkugler/maths-online/sql/editor.IdQuestion
export type IdQuestion = number;
// github.com/benoitkugler/maths-online/sql/editor.IdQuestiongroup
export type IdQuestiongroup = number;
// github.com/benoitkugler/maths-online/sql/reviews.IdReview
export type IdReview = number;
// github.com/benoitkugler/maths-online/sql/homework.IdSheet
export type IdSheet = number;
// github.com/benoitkugler/maths-online/sql/teacher.IdStudent
export type IdStudent = number;
// github.com/benoitkugler/maths-online/sql/tasks.IdTask
export type IdTask = number;
// github.com/benoitkugler/maths-online/sql/teacher.IdTeacher
export type IdTeacher = number;
// github.com/benoitkugler/maths-online/sql/trivial.IdTrivial
export type IdTrivial = number;
// github.com/benoitkugler/maths-online/maths/questions.Interpolated
export type Interpolated = string;
// github.com/benoitkugler/maths-online/sql/reviews.Kind
export enum Kind {
  KQuestion = 0,
  KExercice = 1,
  KTrivial = 2,
}

export const KindLabels: { [key in Kind]: string } = {
  [Kind.KQuestion]: "",
  [Kind.KExercice]: "",
  [Kind.KTrivial]: "",
};

// github.com/benoitkugler/maths-online/maths/repere.LabelPos
export enum LabelPos {
  Top = 0,
  Bottom = 1,
  Left = 2,
  Right = 3,
  TopLeft = 4,
  TopRight = 5,
  BottomRight = 6,
  BottomLeft = 7,
  Hide = 8,
}

export const LabelPosLabels: { [key in LabelPos]: string } = {
  [LabelPos.Top]: "Au dessus",
  [LabelPos.Bottom]: "En dessous",
  [LabelPos.Left]: "A gauche",
  [LabelPos.Right]: "A droite",
  [LabelPos.TopLeft]: "Au dessus, à gauche",
  [LabelPos.TopRight]: "Au dessus, à droite",
  [LabelPos.BottomRight]: "En dessous, à droite",
  [LabelPos.BottomLeft]: "En dessous, à gauche",
  [LabelPos.Hide]: "Masquer la légende",
};

// github.com/benoitkugler/maths-online/prof/trivial.LaunchSessionIn
export interface LaunchSessionIn {
  IdConfig: IdTrivial;
  Groups: number[] | null;
}
// github.com/benoitkugler/maths-online/prof/trivial.LaunchSessionOut
export interface LaunchSessionOut {
  GameIDs: string[] | null;
}
// github.com/benoitkugler/maths-online/prof/editor.ListExercicesOut
export interface ListExercicesOut {
  Groups: ExercicegroupExt[] | null;
  NbGroups: number;
  NbExercices: number;
}
// github.com/benoitkugler/maths-online/prof/editor.ListQuestionsOut
export interface ListQuestionsOut {
  Groups: QuestiongroupExt[] | null;
  NbGroups: number;
  NbQuestions: number;
}
// github.com/benoitkugler/maths-online/prof/teacher.LogginIn
export interface LogginIn {
  Mail: string;
  Password: string;
}
// github.com/benoitkugler/maths-online/prof/teacher.LogginOut
export interface LogginOut {
  Error: string;
  IsPasswordError: boolean;
  Token: string;
}
// github.com/benoitkugler/maths-online/prof/trivial.MonitorOut
export interface MonitorOut {
  Games: GameSummary[] | null;
}
// github.com/benoitkugler/maths-online/sql/tasks.Monoquestion
export interface Monoquestion {
  Id: IdMonoquestion;
  IdQuestion: IdQuestion;
  NbRepeat: number;
  Bareme: number;
}
// github.com/benoitkugler/maths-online/maths/repere.NamedRandomLabeledPoint
export interface NamedRandomLabeledPoint {
  Name: string;
  Point: RandomLabeledPoint;
}
// github.com/benoitkugler/maths-online/sql/homework.Notation
export enum Notation {
  NoNotation = 0,
  SuccessNotation = 1,
}

export const NotationLabels: { [key in Notation]: string } = {
  [Notation.NoNotation]: "no notation",
  [Notation.SuccessNotation]:
    "a question gives point if it has been successfully completed (at least) once",
};

// github.com/benoitkugler/maths-online/maths/questions.NumberFieldBlock
export interface NumberFieldBlock {
  Expression: string;
}
// github.com/benoitkugler/maths-online/sql/editor.OptionalIdExercice
export interface OptionalIdExercice {
  Valid: boolean;
  ID: IdExercice;
}
// github.com/benoitkugler/maths-online/sql/editor.OptionalIdQuestiongroup
export interface OptionalIdQuestiongroup {
  ID: IdQuestiongroup;
  Valid: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions.OrderedListFieldBlock
export interface OrderedListFieldBlock {
  Label: Interpolated;
  Answer: Interpolated[] | null;
  AdditionalProposals: Interpolated[] | null;
}
// github.com/benoitkugler/maths-online/prof/teacher.Origin
export interface Origin {
  AllowPublish: boolean;
  IsPublic: boolean;
  Visibility: Visibility;
}
// github.com/benoitkugler/maths-online/prof/editor.OriginKind
export enum OriginKind {
  All = 0,
  OnlyPersonnal = 1,
  OnlyAdmin = 2,
}

export const OriginKindLabels: { [key in OriginKind]: string } = {
  [OriginKind.All]: "",
  [OriginKind.OnlyPersonnal]: "",
  [OriginKind.OnlyAdmin]: "",
};

// github.com/benoitkugler/maths-online/maths/questions.Parameters
export interface Parameters {
  Variables: RandomParameters;
  Intrinsics: string[] | null;
}

export enum ProofAssertionKind {
  ProofEquality = "ProofEquality",
  ProofInvalid = "ProofInvalid",
  ProofNode = "ProofNode",
  ProofSequence = "ProofSequence",
  ProofStatement = "ProofStatement",
}

// github.com/benoitkugler/maths-online/maths/questions.ProofAssertion
export interface ProofAssertion {
  Kind: ProofAssertionKind;
  Data:
    | ProofEquality
    | ProofInvalid
    | ProofNode
    | ProofSequence
    | ProofStatement;
}
// github.com/benoitkugler/maths-online/maths/questions.ProofAssertions
export type ProofAssertions = ProofAssertion[] | null;
// github.com/benoitkugler/maths-online/maths/questions.ProofEquality
export interface ProofEquality {
  Terms: string;
}
// github.com/benoitkugler/maths-online/maths/questions.ProofFieldBlock
export interface ProofFieldBlock {
  Answer: ProofSequence;
}
// github.com/benoitkugler/maths-online/maths/questions.ProofInvalid
export type ProofInvalid = Record<string, never>;
// github.com/benoitkugler/maths-online/maths/questions.ProofNode
export interface ProofNode {
  Left: ProofAssertion;
  Right: ProofAssertion;
  Op: Binary;
}
// github.com/benoitkugler/maths-online/maths/questions.ProofSequence
export interface ProofSequence {
  Parts: ProofAssertions;
}
// github.com/benoitkugler/maths-online/maths/questions.ProofStatement
export interface ProofStatement {
  Content: Interpolated;
}
// github.com/benoitkugler/maths-online/prof/editor.Query
export interface Query {
  TitleQuery: string;
  Tags: string[] | null;
  Origin: OriginKind;
}
// github.com/benoitkugler/maths-online/sql/editor.Question
export interface Question {
  Id: IdQuestion;
  Page: QuestionPage;
  Subtitle: string;
  Description: string;
  Difficulty: DifficultyTag;
  NeedExercice: OptionalIdExercice;
  IdGroup: OptionalIdQuestiongroup;
}
// github.com/benoitkugler/maths-online/sql/trivial.QuestionCriterion
export type QuestionCriterion = (string[] | null)[] | null;
// github.com/benoitkugler/maths-online/prof/editor.QuestionExerciceUses
export type QuestionExerciceUses = TaskDetails[] | null;
// github.com/benoitkugler/maths-online/prof/editor.QuestionHeader
export interface QuestionHeader {
  Id: IdQuestion;
  Subtitle: string;
  Difficulty: DifficultyTag;
}
// github.com/benoitkugler/maths-online/maths/questions.QuestionPage
export interface QuestionPage {
  enonce: Enonce;
  parameters: Parameters;
}
// github.com/benoitkugler/maths-online/prof/editor.QuestionUpdateVisiblityIn
export interface QuestionUpdateVisiblityIn {
  ID: IdQuestiongroup;
  Public: boolean;
}
// github.com/benoitkugler/maths-online/sql/editor.Questiongroup
export interface Questiongroup {
  Id: IdQuestiongroup;
  Title: string;
  Public: boolean;
  IdTeacher: IdTeacher;
}
// github.com/benoitkugler/maths-online/prof/editor.QuestiongroupExt
export interface QuestiongroupExt {
  Group: Questiongroup;
  Origin: Origin;
  Tags: string[] | null;
  Variants: QuestionHeader[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.RadioFieldBlock
export interface RadioFieldBlock {
  Answer: string;
  Proposals: Interpolated[] | null;
  AsDropDown: boolean;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomArea
export interface RandomArea {
  Color: string;
  Points: string[] | null;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomCircle
export interface RandomCircle {
  Center: RandomCoord;
  Radius: string;
  LineColor: string;
  FillColor: string;
  Legend: string;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomCoord
export interface RandomCoord {
  X: string;
  Y: string;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomDrawings
export interface RandomDrawings {
  Points: NamedRandomLabeledPoint[] | null;
  Segments: RandomSegment[] | null;
  Lines: RandomLine[] | null;
  Circles: RandomCircle[] | null;
  Areas: RandomArea[] | null;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomLabeledPoint
export interface RandomLabeledPoint {
  Color: string;
  Coord: RandomCoord;
  Pos: LabelPos;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomLine
export interface RandomLine {
  Label: string;
  A: string;
  B: string;
  Color: string;
}
// github.com/benoitkugler/maths-online/maths/questions.RandomParameter
export interface RandomParameter {
  expression: string;
  variable: Variable;
}
// github.com/benoitkugler/maths-online/maths/questions.RandomParameters
export type RandomParameters = RandomParameter[] | null;
// github.com/benoitkugler/maths-online/maths/repere.RandomSegment
export interface RandomSegment {
  LabelName: string;
  From: string;
  To: string;
  Color: string;
  LabelPos: LabelPos;
  Kind: SegmentKind;
}
// github.com/benoitkugler/maths-online/prof/homework.ReorderSheetTasksIn
export interface ReorderSheetTasksIn {
  IdSheet: IdSheet;
  Tasks: IdTask[] | null;
}
// github.com/benoitkugler/maths-online/maths/repere.RepereBounds
export interface RepereBounds {
  Width: number;
  Height: number;
  Origin: Coord;
}
// github.com/benoitkugler/maths-online/sql/reviews.Review
export interface Review {
  Id: IdReview;
  Kind: Kind;
}
// github.com/benoitkugler/maths-online/prof/reviews.ReviewComment
export interface ReviewComment {
  Comment: Comment;
  AuthorMail: string;
  IsOwned: boolean;
}
// github.com/benoitkugler/maths-online/prof/reviews.ReviewCreateIn
export interface ReviewCreateIn {
  Kind: Kind;
  Id: number;
}
// github.com/benoitkugler/maths-online/prof/reviews.ReviewExt
export interface ReviewExt {
  Approvals: number[];
  Comments: ReviewComment[] | null;
}
// github.com/benoitkugler/maths-online/prof/reviews.ReviewHeader
export interface ReviewHeader {
  Id: IdReview;
  Title: string;
  Kind: Kind;
  OwnerMail: string;
  NbComments: number;
}
// github.com/benoitkugler/maths-online/prof/reviews.ReviewUpdateApprovalIn
export interface ReviewUpdateApprovalIn {
  IdReview: IdReview;
  Approval: Approval;
}
// github.com/benoitkugler/maths-online/prof/reviews.ReviewUpdateCommentsIn
export interface ReviewUpdateCommentsIn {
  IdReview: IdReview;
  Comments: Comments;
}
// github.com/benoitkugler/maths-online/trivial.RoomID
export type RoomID = string;
// github.com/benoitkugler/maths-online/prof/trivial.RunningSessionMetaOut
export interface RunningSessionMetaOut {
  NbGames: number;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveExerciceAndPreviewIn
export interface SaveExerciceAndPreviewIn {
  OnlyPreview: boolean;
  SessionID: string;
  IdExercice: IdExercice;
  Parameters: Parameters;
  Questions: Question[] | null;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveExerciceAndPreviewOut
export interface SaveExerciceAndPreviewOut {
  Error: ErrQuestionInvalid;
  QuestionIndex: number;
  IsValid: boolean;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveQuestionAndPreviewIn
export interface SaveQuestionAndPreviewIn {
  SessionID: string;
  Id: IdQuestion;
  Page: QuestionPage;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveQuestionAndPreviewOut
export interface SaveQuestionAndPreviewOut {
  Error: ErrQuestionInvalid;
  IsValid: boolean;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveQuestionMetaIn
export interface SaveQuestionMetaIn {
  Question: Question;
}
// github.com/benoitkugler/maths-online/maths/repere.SegmentKind
export enum SegmentKind {
  SKSegment = 0,
  SKVector = 1,
  SKLine = 2,
}

export const SegmentKindLabels: { [key in SegmentKind]: string } = {
  [SegmentKind.SKSegment]: "Segment",
  [SegmentKind.SKVector]: "Vecteur",
  [SegmentKind.SKLine]: "Droite (infinie)",
};

// github.com/benoitkugler/maths-online/sql/homework.Sheet
export interface Sheet {
  Id: IdSheet;
  IdClassroom: IdClassroom;
  Title: string;
  Notation: Notation;
  Activated: boolean;
  Deadline: Time;
}
// github.com/benoitkugler/maths-online/prof/homework.SheetExt
export interface SheetExt {
  Sheet: Sheet;
  Tasks: TaskExt[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.SignSymbol
export enum SignSymbol {
  Nothing = 0,
  Zero = 1,
  ForbiddenValue = 2,
}

export const SignSymbolLabels: { [key in SignSymbol]: string } = {
  [SignSymbol.Nothing]: "",
  [SignSymbol.Zero]: "0",
  [SignSymbol.ForbiddenValue]: "||",
};

// github.com/benoitkugler/maths-online/maths/questions.SignTableBlock
export interface SignTableBlock {
  Label: string;
  FxSymbols: SignSymbol[] | null;
  Xs: string[] | null;
  Signs: boolean[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.SignTableFieldBlock
export interface SignTableFieldBlock {
  Answer: SignTableBlock;
}
// github.com/benoitkugler/maths-online/prof/editor.StartSessionOut
export interface StartSessionOut {
  ID: string;
}
// github.com/benoitkugler/maths-online/sql/teacher.Student
export interface Student {
  Id: IdStudent;
  Name: string;
  Surname: string;
  Birthday: Date;
  TrivialSuccess: number;
  IsClientAttached: boolean;
  id_classroom: IdClassroom;
}
// github.com/benoitkugler/maths-online/prof/teacher.StudentHeader
export interface StudentHeader {
  Id: IdStudent;
  Label: string;
}
// github.com/benoitkugler/maths-online/trivial.Success
export type Success = boolean[];
// github.com/benoitkugler/maths-online/maths/questions.TableBlock
export interface TableBlock {
  HorizontalHeaders: TextPart[] | null;
  VerticalHeaders: TextPart[] | null;
  Values: (TextPart[] | null)[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.TableFieldBlock
export interface TableFieldBlock {
  HorizontalHeaders: TextPart[] | null;
  VerticalHeaders: TextPart[] | null;
  Answer: (string[] | null)[] | null;
}
// github.com/benoitkugler/maths-online/tasks.TaskBareme
export type TaskBareme = number[] | null;
// github.com/benoitkugler/maths-online/prof/editor.TaskDetails
export interface TaskDetails {
  Id: IdTask;
  Sheet: Sheet;
  Classroom: Classroom;
}
// github.com/benoitkugler/maths-online/prof/homework.TaskExt
export interface TaskExt {
  Id: IdTask;
  IdWork: WorkID;
  Title: string;
  Subtitle: string;
  NbProgressions: number;
  Baremes: TaskBareme;
}
// github.com/benoitkugler/maths-online/maths/questions.TextBlock
export interface TextBlock {
  Parts: Interpolated;
  Bold: boolean;
  Italic: boolean;
  Smaller: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions.TextKind
export enum TextKind {
  Text = 0,
  StaticMath = 1,
  Expression = 2,
}

export const TextKindLabels: { [key in TextKind]: string } = {
  [TextKind.Text]: "Text simple",
  [TextKind.StaticMath]: "Code LaTeX",
  [TextKind.Expression]: "Expression",
};

// github.com/benoitkugler/maths-online/maths/questions.TextPart
export interface TextPart {
  Content: string;
  Kind: TextKind;
}
// github.com/benoitkugler/maths-online/maths/questions.TreeFieldBlock
export interface TreeFieldBlock {
  EventsProposals: string[] | null;
  AnswerRoot: TreeNodeAnswer;
}
// github.com/benoitkugler/maths-online/maths/questions.TreeNodeAnswer
export interface TreeNodeAnswer {
  Children: TreeNodeAnswer[] | null;
  Probabilities: string[] | null;
  Value: number;
}
// github.com/benoitkugler/maths-online/sql/trivial.Trivial
export interface Trivial {
  Id: IdTrivial;
  Questions: CategoriesQuestions;
  QuestionTimeout: number;
  ShowDecrassage: boolean;
  Public: boolean;
  IdTeacher: IdTeacher;
  Name: string;
}
// github.com/benoitkugler/maths-online/prof/trivial.TrivialExt
export interface TrivialExt {
  Config: Trivial;
  Origin: Origin;
  NbQuestionsByCategories: number[];
}
// github.com/benoitkugler/maths-online/prof/editor.UpdateExercicegroupTagsIn
export interface UpdateExercicegroupTagsIn {
  Id: IdExercicegroup;
  Tags: string[] | null;
}
// github.com/benoitkugler/maths-online/prof/editor.UpdateQuestiongroupTagsIn
export interface UpdateQuestiongroupTagsIn {
  Id: IdQuestiongroup;
  Tags: string[] | null;
}
// github.com/benoitkugler/maths-online/prof/trivial.UpdateTrivialVisiblityIn
export interface UpdateTrivialVisiblityIn {
  ConfigID: IdTrivial;
  Public: boolean;
}
// github.com/benoitkugler/maths-online/maths/expression.Variable
export interface Variable {
  Indice: string;
  Name: number;
}
// github.com/benoitkugler/maths-online/maths/questions.VariationTableBlock
export interface VariationTableBlock {
  Label: Interpolated;
  Xs: string[] | null;
  Fxs: string[] | null;
}
// github.com/benoitkugler/maths-online/maths/questions.VariationTableFieldBlock
export interface VariationTableFieldBlock {
  Answer: VariationTableBlock;
}
// github.com/benoitkugler/maths-online/maths/questions.VectorFieldBlock
export interface VectorFieldBlock {
  Answer: CoordExpression;
  AcceptColinear: boolean;
  DisplayColumn: boolean;
}
// github.com/benoitkugler/maths-online/maths/questions.VectorPairCriterion
export enum VectorPairCriterion {
  VectorEquals = 0,
  VectorColinear = 1,
  VectorOrthogonal = 2,
}

export const VectorPairCriterionLabels: {
  [key in VectorPairCriterion]: string;
} = {
  [VectorPairCriterion.VectorEquals]: "Vecteurs égaux",
  [VectorPairCriterion.VectorColinear]: "Vecteurs colinéaires",
  [VectorPairCriterion.VectorOrthogonal]: "Vecteurs orthogonaux",
};

// github.com/benoitkugler/maths-online/prof/teacher.Visibility
export enum Visibility {
  Admin = 2,
  Personnal = 1,
  hidden = 0,
}

export const VisibilityLabels: { [key in Visibility]: string } = {
  [Visibility.Admin]: "Officiel",
  [Visibility.Personnal]: "Personnel",
  [Visibility.hidden]: "not accessible by the user",
};

// github.com/benoitkugler/maths-online/tasks.WorkID
export interface WorkID {
  ID: number;
  IsExercice: boolean;
}

class DateTag {
  private _ = "D" as const;
}

// AAAA-MM-YY date format
export type Date_ = string & DateTag;

class TimeTag {
  private _ = "T" as const;
}

// ISO date-time string
export type Time = string & TimeTag;

// github.com/benoitkugler/maths-online/maths/questions.errEnonce
export interface errEnonce {
  Error: string;
  Block: number;
  Vars: { [key: string]: string } | null;
}
// github.com/benoitkugler/maths-online/prof/trivial.stopGame
export interface stopGame {
  ID: RoomID;
  Restart: boolean;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(protected baseUrl: string, protected authToken: string) {}

  abstract handleError(error: any): void;

  abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  protected async rawAskInscription(params: AskInscriptionIn) {
    const fullUrl = this.baseUrl + "/prof/inscription";
    const rep: AxiosResponse<AskInscriptionOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** AskInscription wraps rawAskInscription and handles the error */
  async AskInscription(params: AskInscriptionIn) {
    this.startRequest();
    try {
      const out = await this.rawAskInscription(params);
      this.onSuccessAskInscription(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessAskInscription(data: AskInscriptionOut): void;

  protected async rawValidateInscription(params: { data: string }) {
    const fullUrl = this.baseUrl + "inscription";
    await Axios.get(fullUrl, {
      params: { data: params["data"] },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** ValidateInscription wraps rawValidateInscription and handles the error */
  async ValidateInscription(params: { data: string }) {
    this.startRequest();
    try {
      const out = await this.rawValidateInscription(params);
      this.onSuccessValidateInscription();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessValidateInscription(): void;

  protected async rawLoggin(params: LogginIn) {
    const fullUrl = this.baseUrl + "/prof/loggin";
    const rep: AxiosResponse<LogginOut> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** Loggin wraps rawLoggin and handles the error */
  async Loggin(params: LogginIn) {
    this.startRequest();
    try {
      const out = await this.rawLoggin(params);
      this.onSuccessLoggin(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessLoggin(data: LogginOut): void;

  protected async rawTeacherGetClassrooms() {
    const fullUrl = this.baseUrl + "/api/prof/classrooms";
    const rep: AxiosResponse<ClassroomExt[] | null> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** TeacherGetClassrooms wraps rawTeacherGetClassrooms and handles the error */
  async TeacherGetClassrooms() {
    this.startRequest();
    try {
      const out = await this.rawTeacherGetClassrooms();
      this.onSuccessTeacherGetClassrooms(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherGetClassrooms(
    data: ClassroomExt[] | null
  ): void;

  protected async rawTeacherCreateClassroom() {
    const fullUrl = this.baseUrl + "/api/prof/classrooms";
    await Axios.put(fullUrl, null, { headers: this.getHeaders() });
    return true;
  }

  /** TeacherCreateClassroom wraps rawTeacherCreateClassroom and handles the error */
  async TeacherCreateClassroom() {
    this.startRequest();
    try {
      const out = await this.rawTeacherCreateClassroom();
      this.onSuccessTeacherCreateClassroom();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherCreateClassroom(): void;

  protected async rawTeacherUpdateClassroom(params: Classroom) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms";
    const rep: AxiosResponse<Classroom> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** TeacherUpdateClassroom wraps rawTeacherUpdateClassroom and handles the error */
  async TeacherUpdateClassroom(params: Classroom) {
    this.startRequest();
    try {
      const out = await this.rawTeacherUpdateClassroom(params);
      this.onSuccessTeacherUpdateClassroom(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherUpdateClassroom(data: Classroom): void;

  protected async rawTeacherDeleteClassroom(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms";
    await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** TeacherDeleteClassroom wraps rawTeacherDeleteClassroom and handles the error */
  async TeacherDeleteClassroom(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawTeacherDeleteClassroom(params);
      this.onSuccessTeacherDeleteClassroom();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherDeleteClassroom(): void;

  protected async rawTeacherGetClassroomStudents(params: {
    "id-classroom": number;
  }) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms/students";
    const rep: AxiosResponse<Student[] | null> = await Axios.get(fullUrl, {
      params: { "id-classroom": String(params["id-classroom"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** TeacherGetClassroomStudents wraps rawTeacherGetClassroomStudents and handles the error */
  async TeacherGetClassroomStudents(params: { "id-classroom": number }) {
    this.startRequest();
    try {
      const out = await this.rawTeacherGetClassroomStudents(params);
      this.onSuccessTeacherGetClassroomStudents(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherGetClassroomStudents(
    data: Student[] | null
  ): void;

  protected async rawTeacherAddStudent(params: { "id-classroom": number }) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms/students";
    const rep: AxiosResponse<Student> = await Axios.put(fullUrl, null, {
      params: { "id-classroom": String(params["id-classroom"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** TeacherAddStudent wraps rawTeacherAddStudent and handles the error */
  async TeacherAddStudent(params: { "id-classroom": number }) {
    this.startRequest();
    try {
      const out = await this.rawTeacherAddStudent(params);
      this.onSuccessTeacherAddStudent(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherAddStudent(data: Student): void;

  protected async rawTeacherUpdateStudent(params: Student) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms/students";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** TeacherUpdateStudent wraps rawTeacherUpdateStudent and handles the error */
  async TeacherUpdateStudent(params: Student) {
    this.startRequest();
    try {
      const out = await this.rawTeacherUpdateStudent(params);
      this.onSuccessTeacherUpdateStudent();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherUpdateStudent(): void;

  protected async rawTeacherDeleteStudent(params: { "id-student": number }) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms/students";
    await Axios.delete(fullUrl, {
      params: { "id-student": String(params["id-student"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** TeacherDeleteStudent wraps rawTeacherDeleteStudent and handles the error */
  async TeacherDeleteStudent(params: { "id-student": number }) {
    this.startRequest();
    try {
      const out = await this.rawTeacherDeleteStudent(params);
      this.onSuccessTeacherDeleteStudent();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherDeleteStudent(): void;

  protected async rawTeacherImportStudents(
    params: { "id-classroom": string },
    file: File
  ) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms/students/import";
    const formData = new FormData();
    formData.append("file", file, file.name);
    formData.append("id-classroom", params["id-classroom"]);
    await Axios.post(fullUrl, formData, { headers: this.getHeaders() });
    return true;
  }

  /** TeacherImportStudents wraps rawTeacherImportStudents and handles the error */
  async TeacherImportStudents(params: { "id-classroom": string }, file: File) {
    this.startRequest();
    try {
      const out = await this.rawTeacherImportStudents(params, file);
      this.onSuccessTeacherImportStudents();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherImportStudents(): void;

  protected async rawTeacherGenerateClassroomCode(params: {
    "id-classroom": number;
  }) {
    const fullUrl = this.baseUrl + "/api/prof/classrooms/students/connect";
    const rep: AxiosResponse<GenerateClassroomCodeOut> = await Axios.get(
      fullUrl,
      {
        params: { "id-classroom": String(params["id-classroom"]) },
        headers: this.getHeaders(),
      }
    );
    return rep.data;
  }

  /** TeacherGenerateClassroomCode wraps rawTeacherGenerateClassroomCode and handles the error */
  async TeacherGenerateClassroomCode(params: { "id-classroom": number }) {
    this.startRequest();
    try {
      const out = await this.rawTeacherGenerateClassroomCode(params);
      this.onSuccessTeacherGenerateClassroomCode(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTeacherGenerateClassroomCode(
    data: GenerateClassroomCodeOut
  ): void;

  protected async rawGetTrivialPoursuit() {
    const fullUrl = this.baseUrl + "/api/prof/trivial/config";
    const rep: AxiosResponse<TrivialExt[] | null> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** GetTrivialPoursuit wraps rawGetTrivialPoursuit and handles the error */
  async GetTrivialPoursuit() {
    this.startRequest();
    try {
      const out = await this.rawGetTrivialPoursuit();
      this.onSuccessGetTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessGetTrivialPoursuit(
    data: TrivialExt[] | null
  ): void;

  protected async rawCreateTrivialPoursuit() {
    const fullUrl = this.baseUrl + "/api/prof/trivial/config";
    const rep: AxiosResponse<TrivialExt> = await Axios.put(fullUrl, null, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** CreateTrivialPoursuit wraps rawCreateTrivialPoursuit and handles the error */
  async CreateTrivialPoursuit() {
    this.startRequest();
    try {
      const out = await this.rawCreateTrivialPoursuit();
      this.onSuccessCreateTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessCreateTrivialPoursuit(data: TrivialExt): void;

  protected async rawUpdateTrivialPoursuit(params: Trivial) {
    const fullUrl = this.baseUrl + "/api/prof/trivial/config";
    const rep: AxiosResponse<TrivialExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** UpdateTrivialPoursuit wraps rawUpdateTrivialPoursuit and handles the error */
  async UpdateTrivialPoursuit(params: Trivial) {
    this.startRequest();
    try {
      const out = await this.rawUpdateTrivialPoursuit(params);
      this.onSuccessUpdateTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessUpdateTrivialPoursuit(data: TrivialExt): void;

  protected async rawDeleteTrivialPoursuit(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/trivial/config";
    await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** DeleteTrivialPoursuit wraps rawDeleteTrivialPoursuit and handles the error */
  async DeleteTrivialPoursuit(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawDeleteTrivialPoursuit(params);
      this.onSuccessDeleteTrivialPoursuit();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessDeleteTrivialPoursuit(): void;

  protected async rawUpdateTrivialVisiblity(params: UpdateTrivialVisiblityIn) {
    const fullUrl = this.baseUrl + "/api/prof/trivial/config/visibility";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** UpdateTrivialVisiblity wraps rawUpdateTrivialVisiblity and handles the error */
  async UpdateTrivialVisiblity(params: UpdateTrivialVisiblityIn) {
    this.startRequest();
    try {
      const out = await this.rawUpdateTrivialVisiblity(params);
      this.onSuccessUpdateTrivialVisiblity();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessUpdateTrivialVisiblity(): void;

  protected async rawDuplicateTrivialPoursuit(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/trivial/config/duplicate";
    const rep: AxiosResponse<TrivialExt> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** DuplicateTrivialPoursuit wraps rawDuplicateTrivialPoursuit and handles the error */
  async DuplicateTrivialPoursuit(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawDuplicateTrivialPoursuit(params);
      this.onSuccessDuplicateTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessDuplicateTrivialPoursuit(data: TrivialExt): void;

  protected async rawCheckMissingQuestions(params: CategoriesQuestions) {
    const fullUrl =
      this.baseUrl + "/api/prof/trivial/config/check-missing-questions";
    const rep: AxiosResponse<CheckMissingQuestionsOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** CheckMissingQuestions wraps rawCheckMissingQuestions and handles the error */
  async CheckMissingQuestions(params: CategoriesQuestions) {
    this.startRequest();
    try {
      const out = await this.rawCheckMissingQuestions(params);
      this.onSuccessCheckMissingQuestions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessCheckMissingQuestions(
    data: CheckMissingQuestionsOut
  ): void;

  protected async rawTrivialTeacherMonitor() {
    const fullUrl = this.baseUrl + "/api/prof/trivial/monitor";
    const rep: AxiosResponse<MonitorOut> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** TrivialTeacherMonitor wraps rawTrivialTeacherMonitor and handles the error */
  async TrivialTeacherMonitor() {
    this.startRequest();
    try {
      const out = await this.rawTrivialTeacherMonitor();
      this.onSuccessTrivialTeacherMonitor(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessTrivialTeacherMonitor(data: MonitorOut): void;

  protected async rawGetTrivialRunningSessions() {
    const fullUrl = this.baseUrl + "/api/trivial/sessions";
    const rep: AxiosResponse<RunningSessionMetaOut> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** GetTrivialRunningSessions wraps rawGetTrivialRunningSessions and handles the error */
  async GetTrivialRunningSessions() {
    this.startRequest();
    try {
      const out = await this.rawGetTrivialRunningSessions();
      this.onSuccessGetTrivialRunningSessions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessGetTrivialRunningSessions(
    data: RunningSessionMetaOut
  ): void;

  protected async rawLaunchSessionTrivialPoursuit(params: LaunchSessionIn) {
    const fullUrl = this.baseUrl + "/api/trivial/sessions";
    const rep: AxiosResponse<LaunchSessionOut> = await Axios.put(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** LaunchSessionTrivialPoursuit wraps rawLaunchSessionTrivialPoursuit and handles the error */
  async LaunchSessionTrivialPoursuit(params: LaunchSessionIn) {
    this.startRequest();
    try {
      const out = await this.rawLaunchSessionTrivialPoursuit(params);
      this.onSuccessLaunchSessionTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessLaunchSessionTrivialPoursuit(
    data: LaunchSessionOut
  ): void;

  protected async rawStopTrivialGame(params: stopGame) {
    const fullUrl = this.baseUrl + "/api/trivial/sessions/stop";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** StopTrivialGame wraps rawStopTrivialGame and handles the error */
  async StopTrivialGame(params: stopGame) {
    this.startRequest();
    try {
      const out = await this.rawStopTrivialGame(params);
      this.onSuccessStopTrivialGame();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessStopTrivialGame(): void;

  protected async rawEditorStartSession() {
    const fullUrl = this.baseUrl + "/api/prof/editor/new";
    const rep: AxiosResponse<StartSessionOut> = await Axios.put(fullUrl, null, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorStartSession wraps rawEditorStartSession and handles the error */
  async EditorStartSession() {
    this.startRequest();
    try {
      const out = await this.rawEditorStartSession();
      this.onSuccessEditorStartSession(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorStartSession(data: StartSessionOut): void;

  protected async rawEditorPausePreview(params: { sessionID: string }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/pause-preview";
    await Axios.get(fullUrl, {
      params: { sessionID: params["sessionID"] },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** EditorPausePreview wraps rawEditorPausePreview and handles the error */
  async EditorPausePreview(params: { sessionID: string }) {
    this.startRequest();
    try {
      const out = await this.rawEditorPausePreview(params);
      this.onSuccessEditorPausePreview();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorPausePreview(): void;

  protected async rawEditorGetTags() {
    const fullUrl = this.baseUrl + "/api/prof/editor/tags";
    const rep: AxiosResponse<string[] | null> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorGetTags wraps rawEditorGetTags and handles the error */
  async EditorGetTags() {
    this.startRequest();
    try {
      const out = await this.rawEditorGetTags();
      this.onSuccessEditorGetTags(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorGetTags(data: string[] | null): void;

  protected async rawEditorSearchQuestions(params: Query) {
    const fullUrl = this.baseUrl + "/api/prof/editor/questiongroups";
    const rep: AxiosResponse<ListQuestionsOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorSearchQuestions wraps rawEditorSearchQuestions and handles the error */
  async EditorSearchQuestions(params: Query) {
    this.startRequest();
    try {
      const out = await this.rawEditorSearchQuestions(params);
      this.onSuccessEditorSearchQuestions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSearchQuestions(
    data: ListQuestionsOut
  ): void;

  protected async rawEditorDuplicateQuestion(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/question/duplicate";
    const rep: AxiosResponse<Question> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDuplicateQuestion wraps rawEditorDuplicateQuestion and handles the error */
  async EditorDuplicateQuestion(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDuplicateQuestion(params);
      this.onSuccessEditorDuplicateQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDuplicateQuestion(data: Question): void;

  protected async rawEditorDuplicateQuestiongroup(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/questiongroup/duplicate";
    await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** EditorDuplicateQuestiongroup wraps rawEditorDuplicateQuestiongroup and handles the error */
  async EditorDuplicateQuestiongroup(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDuplicateQuestiongroup(params);
      this.onSuccessEditorDuplicateQuestiongroup();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDuplicateQuestiongroup(): void;

  protected async rawEditorCreateQuestiongroup() {
    const fullUrl = this.baseUrl + "/api/prof/editor/questiongroup";
    const rep: AxiosResponse<QuestiongroupExt> = await Axios.put(
      fullUrl,
      null,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorCreateQuestiongroup wraps rawEditorCreateQuestiongroup and handles the error */
  async EditorCreateQuestiongroup() {
    this.startRequest();
    try {
      const out = await this.rawEditorCreateQuestiongroup();
      this.onSuccessEditorCreateQuestiongroup(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorCreateQuestiongroup(
    data: QuestiongroupExt
  ): void;

  protected async rawEditorUpdateQuestiongroup(params: Questiongroup) {
    const fullUrl = this.baseUrl + "/api/prof/editor/questiongroup";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorUpdateQuestiongroup wraps rawEditorUpdateQuestiongroup and handles the error */
  async EditorUpdateQuestiongroup(params: Questiongroup) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateQuestiongroup(params);
      this.onSuccessEditorUpdateQuestiongroup();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateQuestiongroup(): void;

  protected async rawEditorUpdateQuestionTags(
    params: UpdateQuestiongroupTagsIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/questiongroup/tags";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorUpdateQuestionTags wraps rawEditorUpdateQuestionTags and handles the error */
  async EditorUpdateQuestionTags(params: UpdateQuestiongroupTagsIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateQuestionTags(params);
      this.onSuccessEditorUpdateQuestionTags();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateQuestionTags(): void;

  protected async rawEditorUpdateQuestiongroupVis(
    params: QuestionUpdateVisiblityIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/questiongroup/visibility";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorUpdateQuestiongroupVis wraps rawEditorUpdateQuestiongroupVis and handles the error */
  async EditorUpdateQuestiongroupVis(params: QuestionUpdateVisiblityIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateQuestiongroupVis(params);
      this.onSuccessEditorUpdateQuestiongroupVis();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateQuestiongroupVis(): void;

  protected async rawEditorGetQuestions(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/question";
    const rep: AxiosResponse<Question[] | null> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorGetQuestions wraps rawEditorGetQuestions and handles the error */
  async EditorGetQuestions(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorGetQuestions(params);
      this.onSuccessEditorGetQuestions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorGetQuestions(data: Question[] | null): void;

  protected async rawEditorDeleteQuestion(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/question";
    const rep: AxiosResponse<DeleteQuestionOut> = await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDeleteQuestion wraps rawEditorDeleteQuestion and handles the error */
  async EditorDeleteQuestion(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDeleteQuestion(params);
      this.onSuccessEditorDeleteQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDeleteQuestion(
    data: DeleteQuestionOut
  ): void;

  protected async rawEditorSaveQuestionMeta(params: SaveQuestionMetaIn) {
    const fullUrl = this.baseUrl + "/api/prof/editor/question/variant";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorSaveQuestionMeta wraps rawEditorSaveQuestionMeta and handles the error */
  async EditorSaveQuestionMeta(params: SaveQuestionMetaIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorSaveQuestionMeta(params);
      this.onSuccessEditorSaveQuestionMeta();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSaveQuestionMeta(): void;

  protected async rawEditorCheckQuestionParameters(
    params: CheckQuestionParametersIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/question/check-params";
    const rep: AxiosResponse<CheckQuestionParametersOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorCheckQuestionParameters wraps rawEditorCheckQuestionParameters and handles the error */
  async EditorCheckQuestionParameters(params: CheckQuestionParametersIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorCheckQuestionParameters(params);
      this.onSuccessEditorCheckQuestionParameters(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorCheckQuestionParameters(
    data: CheckQuestionParametersOut
  ): void;

  protected async rawEditorSaveQuestionAndPreview(
    params: SaveQuestionAndPreviewIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/question/preview";
    const rep: AxiosResponse<SaveQuestionAndPreviewOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorSaveQuestionAndPreview wraps rawEditorSaveQuestionAndPreview and handles the error */
  async EditorSaveQuestionAndPreview(params: SaveQuestionAndPreviewIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorSaveQuestionAndPreview(params);
      this.onSuccessEditorSaveQuestionAndPreview(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSaveQuestionAndPreview(
    data: SaveQuestionAndPreviewOut
  ): void;

  protected async rawEditorSearchExercices(params: Query) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercicegroups";
    const rep: AxiosResponse<ListExercicesOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorSearchExercices wraps rawEditorSearchExercices and handles the error */
  async EditorSearchExercices(params: Query) {
    this.startRequest();
    try {
      const out = await this.rawEditorSearchExercices(params);
      this.onSuccessEditorSearchExercices(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSearchExercices(
    data: ListExercicesOut
  ): void;

  protected async rawEditorUpdateExercicegroup(params: Exercicegroup) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercicegroup";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorUpdateExercicegroup wraps rawEditorUpdateExercicegroup and handles the error */
  async EditorUpdateExercicegroup(params: Exercicegroup) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateExercicegroup(params);
      this.onSuccessEditorUpdateExercicegroup();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateExercicegroup(): void;

  protected async rawEditorUpdateExerciceTags(
    params: UpdateExercicegroupTagsIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercicegroup/tags";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorUpdateExerciceTags wraps rawEditorUpdateExerciceTags and handles the error */
  async EditorUpdateExerciceTags(params: UpdateExercicegroupTagsIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateExerciceTags(params);
      this.onSuccessEditorUpdateExerciceTags();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateExerciceTags(): void;

  protected async rawEditorDuplicateExercicegroup(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercicegroup/duplicate";
    await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** EditorDuplicateExercicegroup wraps rawEditorDuplicateExercicegroup and handles the error */
  async EditorDuplicateExercicegroup(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDuplicateExercicegroup(params);
      this.onSuccessEditorDuplicateExercicegroup();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDuplicateExercicegroup(): void;

  protected async rawEditorGetExerciceContent(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice";
    const rep: AxiosResponse<ExerciceExt> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorGetExerciceContent wraps rawEditorGetExerciceContent and handles the error */
  async EditorGetExerciceContent(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorGetExerciceContent(params);
      this.onSuccessEditorGetExerciceContent(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorGetExerciceContent(data: ExerciceExt): void;

  protected async rawEditorCreateExercice() {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice";
    const rep: AxiosResponse<ExercicegroupExt> = await Axios.put(
      fullUrl,
      null,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorCreateExercice wraps rawEditorCreateExercice and handles the error */
  async EditorCreateExercice() {
    this.startRequest();
    try {
      const out = await this.rawEditorCreateExercice();
      this.onSuccessEditorCreateExercice(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorCreateExercice(
    data: ExercicegroupExt
  ): void;

  protected async rawEditorDeleteExercice(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice";
    const rep: AxiosResponse<DeleteExerciceOut> = await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDeleteExercice wraps rawEditorDeleteExercice and handles the error */
  async EditorDeleteExercice(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDeleteExercice(params);
      this.onSuccessEditorDeleteExercice(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDeleteExercice(
    data: DeleteExerciceOut
  ): void;

  protected async rawEditorSaveExerciceMeta(params: Exercice) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice";
    const rep: AxiosResponse<Exercice> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorSaveExerciceMeta wraps rawEditorSaveExerciceMeta and handles the error */
  async EditorSaveExerciceMeta(params: Exercice) {
    this.startRequest();
    try {
      const out = await this.rawEditorSaveExerciceMeta(params);
      this.onSuccessEditorSaveExerciceMeta(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSaveExerciceMeta(data: Exercice): void;

  protected async rawEditorDuplicateExercice(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice/duplicate";
    const rep: AxiosResponse<ExerciceHeader> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDuplicateExercice wraps rawEditorDuplicateExercice and handles the error */
  async EditorDuplicateExercice(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDuplicateExercice(params);
      this.onSuccessEditorDuplicateExercice(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDuplicateExercice(
    data: ExerciceHeader
  ): void;

  protected async rawEditorExerciceCreateQuestion(
    params: ExerciceCreateQuestionIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice/questions";
    const rep: AxiosResponse<ExerciceExt> = await Axios.put(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorExerciceCreateQuestion wraps rawEditorExerciceCreateQuestion and handles the error */
  async EditorExerciceCreateQuestion(params: ExerciceCreateQuestionIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorExerciceCreateQuestion(params);
      this.onSuccessEditorExerciceCreateQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorExerciceCreateQuestion(
    data: ExerciceExt
  ): void;

  protected async rawEditorExerciceImportQuestion(
    params: ExerciceImportQuestionIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice/questions/import";
    const rep: AxiosResponse<ExerciceExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorExerciceImportQuestion wraps rawEditorExerciceImportQuestion and handles the error */
  async EditorExerciceImportQuestion(params: ExerciceImportQuestionIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorExerciceImportQuestion(params);
      this.onSuccessEditorExerciceImportQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorExerciceImportQuestion(
    data: ExerciceExt
  ): void;

  protected async rawEditorExerciceDuplicateQuestion(
    params: ExerciceDuplicateQuestionIn
  ) {
    const fullUrl =
      this.baseUrl + "/api/prof/editor/exercice/questions/duplicate";
    const rep: AxiosResponse<ExerciceExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorExerciceDuplicateQuestion wraps rawEditorExerciceDuplicateQuestion and handles the error */
  async EditorExerciceDuplicateQuestion(params: ExerciceDuplicateQuestionIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorExerciceDuplicateQuestion(params);
      this.onSuccessEditorExerciceDuplicateQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorExerciceDuplicateQuestion(
    data: ExerciceExt
  ): void;

  protected async rawEditorExerciceUpdateQuestions(
    params: ExerciceUpdateQuestionsIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice/questions";
    const rep: AxiosResponse<ExerciceExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorExerciceUpdateQuestions wraps rawEditorExerciceUpdateQuestions and handles the error */
  async EditorExerciceUpdateQuestions(params: ExerciceUpdateQuestionsIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorExerciceUpdateQuestions(params);
      this.onSuccessEditorExerciceUpdateQuestions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorExerciceUpdateQuestions(
    data: ExerciceExt
  ): void;

  protected async rawEditorUpdateExercicegroupVis(
    params: ExerciceUpdateVisiblityIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercicegroup/visibility";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** EditorUpdateExercicegroupVis wraps rawEditorUpdateExercicegroupVis and handles the error */
  async EditorUpdateExercicegroupVis(params: ExerciceUpdateVisiblityIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateExercicegroupVis(params);
      this.onSuccessEditorUpdateExercicegroupVis();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateExercicegroupVis(): void;

  protected async rawEditorCheckExerciceParameters(
    params: CheckExerciceParametersIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice/check-params";
    const rep: AxiosResponse<CheckExerciceParametersOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorCheckExerciceParameters wraps rawEditorCheckExerciceParameters and handles the error */
  async EditorCheckExerciceParameters(params: CheckExerciceParametersIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorCheckExerciceParameters(params);
      this.onSuccessEditorCheckExerciceParameters(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorCheckExerciceParameters(
    data: CheckExerciceParametersOut
  ): void;

  protected async rawEditorSaveExerciceAndPreview(
    params: SaveExerciceAndPreviewIn
  ) {
    const fullUrl = this.baseUrl + "/api/prof/editor/exercice/preview";
    const rep: AxiosResponse<SaveExerciceAndPreviewOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorSaveExerciceAndPreview wraps rawEditorSaveExerciceAndPreview and handles the error */
  async EditorSaveExerciceAndPreview(params: SaveExerciceAndPreviewIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorSaveExerciceAndPreview(params);
      this.onSuccessEditorSaveExerciceAndPreview(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSaveExerciceAndPreview(
    data: SaveExerciceAndPreviewOut
  ): void;

  protected async rawHomeworkGetSheets() {
    const fullUrl = this.baseUrl + "/api/prof/homework";
    const rep: AxiosResponse<ClassroomSheets[] | null> = await Axios.get(
      fullUrl,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** HomeworkGetSheets wraps rawHomeworkGetSheets and handles the error */
  async HomeworkGetSheets() {
    this.startRequest();
    try {
      const out = await this.rawHomeworkGetSheets();
      this.onSuccessHomeworkGetSheets(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkGetSheets(
    data: ClassroomSheets[] | null
  ): void;

  protected async rawHomeworkCreateSheet(params: CreateSheetIn) {
    const fullUrl = this.baseUrl + "/api/prof/homework";
    const rep: AxiosResponse<SheetExt> = await Axios.put(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** HomeworkCreateSheet wraps rawHomeworkCreateSheet and handles the error */
  async HomeworkCreateSheet(params: CreateSheetIn) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkCreateSheet(params);
      this.onSuccessHomeworkCreateSheet(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkCreateSheet(data: SheetExt): void;

  protected async rawHomeworkUpdateSheet(params: Sheet) {
    const fullUrl = this.baseUrl + "/api/prof/homework";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** HomeworkUpdateSheet wraps rawHomeworkUpdateSheet and handles the error */
  async HomeworkUpdateSheet(params: Sheet) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkUpdateSheet(params);
      this.onSuccessHomeworkUpdateSheet();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkUpdateSheet(): void;

  protected async rawHomeworkDeleteSheet(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/homework";
    await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** HomeworkDeleteSheet wraps rawHomeworkDeleteSheet and handles the error */
  async HomeworkDeleteSheet(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkDeleteSheet(params);
      this.onSuccessHomeworkDeleteSheet();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkDeleteSheet(): void;

  protected async rawHomeworkCopySheet(params: CopySheetIn) {
    const fullUrl = this.baseUrl + "/api/prof/homework/copy-sheet";
    const rep: AxiosResponse<SheetExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** HomeworkCopySheet wraps rawHomeworkCopySheet and handles the error */
  async HomeworkCopySheet(params: CopySheetIn) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkCopySheet(params);
      this.onSuccessHomeworkCopySheet(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkCopySheet(data: SheetExt): void;

  protected async rawHomeworkRemoveTask(params: { "id-task": number }) {
    const fullUrl = this.baseUrl + "/api/prof/homework/sheet";
    await Axios.delete(fullUrl, {
      params: { "id-task": String(params["id-task"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** HomeworkRemoveTask wraps rawHomeworkRemoveTask and handles the error */
  async HomeworkRemoveTask(params: { "id-task": number }) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkRemoveTask(params);
      this.onSuccessHomeworkRemoveTask();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkRemoveTask(): void;

  protected async rawHomeworkAddExercice(params: AddExerciceToTaskIn) {
    const fullUrl = this.baseUrl + "/api/prof/homework/sheet/exercice";
    const rep: AxiosResponse<TaskExt> = await Axios.put(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** HomeworkAddExercice wraps rawHomeworkAddExercice and handles the error */
  async HomeworkAddExercice(params: AddExerciceToTaskIn) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkAddExercice(params);
      this.onSuccessHomeworkAddExercice(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkAddExercice(data: TaskExt): void;

  protected async rawHomeworkAddMonoquestion(params: AddMonoquestionToTaskIn) {
    const fullUrl = this.baseUrl + "/api/prof/homework/sheet/monoquestion";
    const rep: AxiosResponse<TaskExt> = await Axios.put(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** HomeworkAddMonoquestion wraps rawHomeworkAddMonoquestion and handles the error */
  async HomeworkAddMonoquestion(params: AddMonoquestionToTaskIn) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkAddMonoquestion(params);
      this.onSuccessHomeworkAddMonoquestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkAddMonoquestion(data: TaskExt): void;

  protected async rawHomeworkUpdateMonoquestion(params: Monoquestion) {
    const fullUrl = this.baseUrl + "/api/prof/homework/sheet/monoquestion";
    const rep: AxiosResponse<TaskExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** HomeworkUpdateMonoquestion wraps rawHomeworkUpdateMonoquestion and handles the error */
  async HomeworkUpdateMonoquestion(params: Monoquestion) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkUpdateMonoquestion(params);
      this.onSuccessHomeworkUpdateMonoquestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkUpdateMonoquestion(data: TaskExt): void;

  protected async rawHomeworkReorderSheetTasks(params: ReorderSheetTasksIn) {
    const fullUrl = this.baseUrl + "/api/prof/homework/sheet";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** HomeworkReorderSheetTasks wraps rawHomeworkReorderSheetTasks and handles the error */
  async HomeworkReorderSheetTasks(params: ReorderSheetTasksIn) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkReorderSheetTasks(params);
      this.onSuccessHomeworkReorderSheetTasks();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkReorderSheetTasks(): void;

  protected async rawHomeworkGetMarks(params: HowemorkMarksIn) {
    const fullUrl = this.baseUrl + "/api/prof/homework/marks";
    const rep: AxiosResponse<HomeworkMarksOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** HomeworkGetMarks wraps rawHomeworkGetMarks and handles the error */
  async HomeworkGetMarks(params: HowemorkMarksIn) {
    this.startRequest();
    try {
      const out = await this.rawHomeworkGetMarks(params);
      this.onSuccessHomeworkGetMarks(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessHomeworkGetMarks(data: HomeworkMarksOut): void;

  protected async rawReviewCreate(params: ReviewCreateIn) {
    const fullUrl = this.baseUrl + "/api/prof/review";
    const rep: AxiosResponse<Review> = await Axios.put(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** ReviewCreate wraps rawReviewCreate and handles the error */
  async ReviewCreate(params: ReviewCreateIn) {
    this.startRequest();
    try {
      const out = await this.rawReviewCreate(params);
      this.onSuccessReviewCreate(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewCreate(data: Review): void;

  protected async rawReviewsList() {
    const fullUrl = this.baseUrl + "/api/prof/reviews";
    const rep: AxiosResponse<ReviewHeader[] | null> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** ReviewsList wraps rawReviewsList and handles the error */
  async ReviewsList() {
    this.startRequest();
    try {
      const out = await this.rawReviewsList();
      this.onSuccessReviewsList(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewsList(data: ReviewHeader[] | null): void;

  protected async rawReviewsLoad(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/review";
    const rep: AxiosResponse<ReviewExt> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** ReviewsLoad wraps rawReviewsLoad and handles the error */
  async ReviewsLoad(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawReviewsLoad(params);
      this.onSuccessReviewsLoad(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewsLoad(data: ReviewExt): void;

  protected async rawReviewDelete(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/review";
    await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** ReviewDelete wraps rawReviewDelete and handles the error */
  async ReviewDelete(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawReviewDelete(params);
      this.onSuccessReviewDelete();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewDelete(): void;

  protected async rawReviewUpdateApproval(params: ReviewUpdateApprovalIn) {
    const fullUrl = this.baseUrl + "/api/prof/review/approval";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** ReviewUpdateApproval wraps rawReviewUpdateApproval and handles the error */
  async ReviewUpdateApproval(params: ReviewUpdateApprovalIn) {
    this.startRequest();
    try {
      const out = await this.rawReviewUpdateApproval(params);
      this.onSuccessReviewUpdateApproval();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewUpdateApproval(): void;

  protected async rawReviewUpdateCommnents(params: ReviewUpdateCommentsIn) {
    const fullUrl = this.baseUrl + "/api/prof/review/comments";
    await Axios.post(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** ReviewUpdateCommnents wraps rawReviewUpdateCommnents and handles the error */
  async ReviewUpdateCommnents(params: ReviewUpdateCommentsIn) {
    this.startRequest();
    try {
      const out = await this.rawReviewUpdateCommnents(params);
      this.onSuccessReviewUpdateCommnents();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewUpdateCommnents(): void;

  protected async rawReviewAccept(params: { id: number }) {
    const fullUrl = this.baseUrl + "/api/prof/review/accept";
    await Axios.post(fullUrl, null, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return true;
  }

  /** ReviewAccept wraps rawReviewAccept and handles the error */
  async ReviewAccept(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawReviewAccept(params);
      this.onSuccessReviewAccept();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessReviewAccept(): void;
}
