// Code generated by apigen. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

// github.com/benoitkugler/maths-online/prof/teacher.AskInscriptionIn
export interface AskInscriptionIn {
  Mail: string;
  Password: string;
}
// github.com/benoitkugler/maths-online/prof/teacher.LogginIn
export interface LogginIn {
  Mail: string;
  Password: string;
}
// github.com/benoitkugler/maths-online/prof/teacher.LogginOut
export interface LogginOut {
  Error: string;
  Token: string;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.QuestionCriterion
export type QuestionCriterion = (string[] | null)[] | null;
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.CategoriesQuestions
export type CategoriesQuestions = QuestionCriterion[];
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.TrivialConfig
export interface TrivialConfig {
  Id: number;
  Questions: CategoriesQuestions;
  QuestionTimeout: number;
  ShowDecrassage: boolean;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.LaunchSessionOut
export interface LaunchSessionOut {
  SessionID: string;
  GroupsID: string[] | null;
  GroupStrategyKind: number;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.TrivialConfigExt
export interface TrivialConfigExt {
  Config: TrivialConfig;
  Running: LaunchSessionOut;
  NbQuestionsByCategories: number[];
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.CheckMissingQuestionsOut
export interface CheckMissingQuestionsOut {
  Pattern: string[] | null;
  Missing: (string[] | null)[] | null;
}

export enum GroupStrategyKind {
  FixedSizeGroupStrategy = 0,
  RandomGroupStrategy = 1,
}

export interface GroupStrategy {
  Kind: GroupStrategyKind;
  Data: FixedSizeGroupStrategy | RandomGroupStrategy;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.FixedSizeGroupStrategy
export interface FixedSizeGroupStrategy {
  Groups: number[] | null;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.RandomGroupStrategy
export interface RandomGroupStrategy {
  MaxPlayersPerGroup: number;
  TotalPlayersNumber: number;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.LaunchSessionIn
export interface LaunchSessionIn {
  IdConfig: number;
  GroupStrategy: GroupStrategy;
}
// github.com/benoitkugler/maths-online/prof/editor.StartSessionOut
export interface StartSessionOut {
  ID: string;
}
// github.com/benoitkugler/maths-online/prof/editor.ListQuestionsIn
export interface ListQuestionsIn {
  TitleQuery: string;
  Tags: string[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.DifficultyTag
export type DifficultyTag = string;
// github.com/benoitkugler/maths-online/prof/editor.QuestionHeader
export interface QuestionHeader {
  Title: string;
  Tags: string[] | null;
  Id: number;
  Difficulty: DifficultyTag;
  IsInGroup: boolean;
}
// github.com/benoitkugler/maths-online/prof/editor.QuestionGroup
export interface QuestionGroup {
  Title: string;
  Questions: QuestionHeader[] | null;
  Size: number;
}
// github.com/benoitkugler/maths-online/prof/editor.ListQuestionsOut
export interface ListQuestionsOut {
  Questions: QuestionGroup[] | null;
  Size: number;
}

export enum BlockKind {
  ExpressionFieldBlock = 0,
  FigureAffineLineFieldBlock = 1,
  FigureBlock = 2,
  FigurePointFieldBlock = 3,
  FigureVectorFieldBlock = 4,
  FigureVectorPairFieldBlock = 5,
  FormulaBlock = 6,
  FunctionGraphBlock = 7,
  FunctionPointsFieldBlock = 8,
  FunctionVariationGraphBlock = 9,
  NumberFieldBlock = 10,
  OrderedListFieldBlock = 11,
  RadioFieldBlock = 12,
  SignTableBlock = 13,
  TableBlock = 14,
  TableFieldBlock = 15,
  TextBlock = 16,
  TreeFieldBlock = 17,
  VariationTableBlock = 18,
  VariationTableFieldBlock = 19,
}

export interface Block {
  Kind: BlockKind;
  Data:
    | ExpressionFieldBlock
    | FigureAffineLineFieldBlock
    | FigureBlock
    | FigurePointFieldBlock
    | FigureVectorFieldBlock
    | FigureVectorPairFieldBlock
    | FormulaBlock
    | FunctionGraphBlock
    | FunctionPointsFieldBlock
    | FunctionVariationGraphBlock
    | NumberFieldBlock
    | OrderedListFieldBlock
    | RadioFieldBlock
    | SignTableBlock
    | TableBlock
    | TableFieldBlock
    | TextBlock
    | TreeFieldBlock
    | VariationTableBlock
    | VariationTableFieldBlock;
}
// github.com/benoitkugler/maths-online/maths/exercice.TextKind
export type TextKind = number;
// github.com/benoitkugler/maths-online/maths/exercice.TextPart
export interface TextPart {
  Content: string;
  Kind: TextKind;
}
// github.com/benoitkugler/maths-online/maths/expression.ComparisonLevel
export type ComparisonLevel = number;
// github.com/benoitkugler/maths-online/maths/exercice.ExpressionFieldBlock
export interface ExpressionFieldBlock {
  Expression: string;
  Label: TextPart;
  ComparisonLevel: ComparisonLevel;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomCoord
export interface RandomCoord {
  X: string;
  Y: string;
}
// github.com/benoitkugler/maths-online/maths/repere.LabelPos
export type LabelPos = number;
// github.com/benoitkugler/maths-online/maths/repere.RandomLabeledPoint
export interface RandomLabeledPoint {
  Coord: RandomCoord;
  Pos: LabelPos;
}
// github.com/benoitkugler/maths-online/maths/repere.NamedRandomLabeledPoint
export interface NamedRandomLabeledPoint {
  Name: string;
  Point: RandomLabeledPoint;
}
// github.com/benoitkugler/maths-online/maths/repere.Segment
export interface Segment {
  LabelName: string;
  From: string;
  To: string;
  LabelPos: LabelPos;
  AsVector: boolean;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomLine
export interface RandomLine {
  Label: string;
  A: string;
  B: string;
  Color: string;
}
// github.com/benoitkugler/maths-online/maths/repere.RandomDrawings
export interface RandomDrawings {
  Points: NamedRandomLabeledPoint[] | null;
  Segments: Segment[] | null;
  Lines: RandomLine[] | null;
}
// github.com/benoitkugler/maths-online/maths/repere.Coord
export interface Coord {
  X: number;
  Y: number;
}
// github.com/benoitkugler/maths-online/maths/repere.RepereBounds
export interface RepereBounds {
  Width: number;
  Height: number;
  Origin: Coord;
}
// github.com/benoitkugler/maths-online/maths/exercice.FigureBlock
export interface FigureBlock {
  Drawings: RandomDrawings;
  Bounds: RepereBounds;
  ShowGrid: boolean;
}
// github.com/benoitkugler/maths-online/maths/exercice.FigureAffineLineFieldBlock
export interface FigureAffineLineFieldBlock {
  Label: string;
  A: string;
  B: string;
  Figure: FigureBlock;
}
// github.com/benoitkugler/maths-online/maths/exercice.CoordExpression
export interface CoordExpression {
  X: string;
  Y: string;
}
// github.com/benoitkugler/maths-online/maths/exercice.FigurePointFieldBlock
export interface FigurePointFieldBlock {
  Answer: CoordExpression;
  Figure: FigureBlock;
}
// github.com/benoitkugler/maths-online/maths/exercice.FigureVectorFieldBlock
export interface FigureVectorFieldBlock {
  Answer: CoordExpression;
  AnswerOrigin: CoordExpression;
  Figure: FigureBlock;
  MustHaveOrigin: boolean;
}
// github.com/benoitkugler/maths-online/maths/exercice.VectorPairCriterion
export type VectorPairCriterion = number;
// github.com/benoitkugler/maths-online/maths/exercice.FigureVectorPairFieldBlock
export interface FigureVectorPairFieldBlock {
  Figure: FigureBlock;
  Criterion: VectorPairCriterion;
}
// github.com/benoitkugler/maths-online/maths/exercice.Interpolated
export type Interpolated = string;
// github.com/benoitkugler/maths-online/maths/exercice.FormulaBlock
export interface FormulaBlock {
  Parts: Interpolated;
}
// github.com/benoitkugler/maths-online/maths/function_grapher.FunctionDecoration
export interface FunctionDecoration {
  Label: string;
  Color: string;
}
// github.com/benoitkugler/maths-online/maths/expression.Variable
export interface Variable {
  Indice: string;
  Name: number;
}
// github.com/benoitkugler/maths-online/maths/exercice.FunctionDefinition
export interface FunctionDefinition {
  Function: string;
  Decoration: FunctionDecoration;
  Variable: Variable;
  Range: number[];
}
// github.com/benoitkugler/maths-online/maths/exercice.FunctionGraphBlock
export interface FunctionGraphBlock {
  Functions: FunctionDefinition[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.FunctionPointsFieldBlock
export interface FunctionPointsFieldBlock {
  Function: string;
  Label: string;
  Variable: Variable;
  XGrid: number[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.VariationTableBlock
export interface VariationTableBlock {
  Label: string;
  Xs: string[] | null;
  Fxs: string[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.FunctionVariationGraphBlock
export type FunctionVariationGraphBlock = VariationTableBlock;
// github.com/benoitkugler/maths-online/maths/exercice.NumberFieldBlock
export interface NumberFieldBlock {
  Expression: string;
}
// github.com/benoitkugler/maths-online/maths/exercice.OrderedListFieldBlock
export interface OrderedListFieldBlock {
  Label: string;
  Answer: Interpolated[] | null;
  AdditionalProposals: Interpolated[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.RadioFieldBlock
export interface RadioFieldBlock {
  Answer: string;
  Proposals: Interpolated[] | null;
  AsDropDown: boolean;
}
// github.com/benoitkugler/maths-online/maths/exercice.SignSymbol
export type SignSymbol = number;
// github.com/benoitkugler/maths-online/maths/exercice.SignTableBlock
export interface SignTableBlock {
  Label: string;
  FxSymbols: SignSymbol[] | null;
  Xs: Interpolated[] | null;
  Signs: boolean[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.TableBlock
export interface TableBlock {
  HorizontalHeaders: TextPart[] | null;
  VerticalHeaders: TextPart[] | null;
  Values: (TextPart[] | null)[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.TableFieldBlock
export interface TableFieldBlock {
  HorizontalHeaders: TextPart[] | null;
  VerticalHeaders: TextPart[] | null;
  Answer: (string[] | null)[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.TextBlock
export interface TextBlock {
  Parts: Interpolated;
  Bold: boolean;
  Italic: boolean;
  Smaller: boolean;
}
// github.com/benoitkugler/maths-online/maths/exercice.TreeNodeAnswer
export interface TreeNodeAnswer {
  Children: TreeNodeAnswer[] | null;
  Probabilities: string[] | null;
  Value: number;
}
// github.com/benoitkugler/maths-online/maths/exercice.TreeFieldBlock
export interface TreeFieldBlock {
  EventsProposals: string[] | null;
  AnswerRoot: TreeNodeAnswer;
}
// github.com/benoitkugler/maths-online/maths/exercice.VariationTableFieldBlock
export interface VariationTableFieldBlock {
  Answer: VariationTableBlock;
}
// github.com/benoitkugler/maths-online/maths/exercice.Enonce
export type Enonce = Block[] | null;
// github.com/benoitkugler/maths-online/maths/exercice.randomParameter
export interface randomParameter {
  expression: string;
  variable: Variable;
}
// github.com/benoitkugler/maths-online/maths/exercice.randomParameters
export type randomParameters = randomParameter[] | null;
// github.com/benoitkugler/maths-online/maths/exercice.Parameters
export interface Parameters {
  Variables: randomParameters;
  Intrinsics: string[] | null;
}
// github.com/benoitkugler/maths-online/maths/exercice.Question
export interface Question {
  id: number;
  title: string;
  enonce: Enonce;
  parameters: Parameters;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveAndPreviewIn
export interface SaveAndPreviewIn {
  SessionID: string;
  Question: Question;
}
// github.com/benoitkugler/maths-online/maths/exercice.ErrParameters
export interface ErrParameters {
  Origin: string;
  Details: string;
}
// github.com/benoitkugler/maths-online/maths/exercice.errEnonce
export interface errEnonce {
  Error: string;
  Block: number;
}
// github.com/benoitkugler/maths-online/maths/exercice.ErrQuestionInvalid
export interface ErrQuestionInvalid {
  ErrParameters: ErrParameters;
  ErrEnonce: errEnonce;
  ParametersInvalid: boolean;
}
// github.com/benoitkugler/maths-online/prof/editor.SaveAndPreviewOut
export interface SaveAndPreviewOut {
  Error: ErrQuestionInvalid;
  IsValid: boolean;
}
// github.com/benoitkugler/maths-online/prof/editor.UpdateTagsIn
export interface UpdateTagsIn {
  Tags: string[] | null;
  IdQuestion: number;
}
// github.com/benoitkugler/maths-online/prof/editor.CheckParametersIn
export interface CheckParametersIn {
  SessionID: string;
  Parameters: Parameters;
}
// github.com/benoitkugler/maths-online/prof/editor.CheckParametersOut
export interface CheckParametersOut {
  ErrDefinition: ErrParameters;
  Variables: Variable[] | null;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
    protected urlParams: {}
  ) {}

  abstract handleError(error: any): void;

  abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  protected async rawAskInscription(params: AskInscriptionIn) {
    const fullUrl = this.baseUrl + "/prof/inscription";
    const rep: AxiosResponse<any> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** AskInscription wraps rawAskInscription and handles the error */
  async AskInscription(params: AskInscriptionIn) {
    this.startRequest();
    try {
      const out = await this.rawAskInscription(params);
      this.onSuccessAskInscription(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessAskInscription(data: any): void;

  protected async rawValidateInscription(params: { data: string }) {
    const fullUrl = this.baseUrl + "inscription";
    const rep: AxiosResponse<any> = await Axios.get(fullUrl, {
      params: { data: params["data"] },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** ValidateInscription wraps rawValidateInscription and handles the error */
  async ValidateInscription(params: { data: string }) {
    this.startRequest();
    try {
      const out = await this.rawValidateInscription(params);
      this.onSuccessValidateInscription(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessValidateInscription(data: any): void;

  protected async rawLoggin(params: LogginIn) {
    const fullUrl = this.baseUrl + "/prof/loggin";
    const rep: AxiosResponse<LogginOut> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** Loggin wraps rawLoggin and handles the error */
  async Loggin(params: LogginIn) {
    this.startRequest();
    try {
      const out = await this.rawLoggin(params);
      this.onSuccessLoggin(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessLoggin(data: LogginOut): void;

  protected async rawGetTrivialPoursuit() {
    const fullUrl = this.baseUrl + "/prof/trivial/config";
    const rep: AxiosResponse<TrivialConfigExt[] | null> = await Axios.get(
      fullUrl,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** GetTrivialPoursuit wraps rawGetTrivialPoursuit and handles the error */
  async GetTrivialPoursuit() {
    this.startRequest();
    try {
      const out = await this.rawGetTrivialPoursuit();
      this.onSuccessGetTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessGetTrivialPoursuit(
    data: TrivialConfigExt[] | null
  ): void;

  protected async rawCreateTrivialPoursuit(params: any) {
    const fullUrl = this.baseUrl + "/prof/trivial/config";
    const rep: AxiosResponse<TrivialConfigExt> = await Axios.put(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** CreateTrivialPoursuit wraps rawCreateTrivialPoursuit and handles the error */
  async CreateTrivialPoursuit(params: any) {
    this.startRequest();
    try {
      const out = await this.rawCreateTrivialPoursuit(params);
      this.onSuccessCreateTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessCreateTrivialPoursuit(
    data: TrivialConfigExt
  ): void;

  protected async rawUpdateTrivialPoursuit(params: TrivialConfig) {
    const fullUrl = this.baseUrl + "/prof/trivial/config";
    const rep: AxiosResponse<TrivialConfigExt> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** UpdateTrivialPoursuit wraps rawUpdateTrivialPoursuit and handles the error */
  async UpdateTrivialPoursuit(params: TrivialConfig) {
    this.startRequest();
    try {
      const out = await this.rawUpdateTrivialPoursuit(params);
      this.onSuccessUpdateTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessUpdateTrivialPoursuit(
    data: TrivialConfigExt
  ): void;

  protected async rawDeleteTrivialPoursuit(params: { id: number }) {
    const fullUrl = this.baseUrl + "/prof/trivial/config";
    const rep: AxiosResponse<any> = await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** DeleteTrivialPoursuit wraps rawDeleteTrivialPoursuit and handles the error */
  async DeleteTrivialPoursuit(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawDeleteTrivialPoursuit(params);
      this.onSuccessDeleteTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessDeleteTrivialPoursuit(data: any): void;

  protected async rawDuplicateTrivialPoursuit(params: { id: number }) {
    const fullUrl = this.baseUrl + "/prof/trivial/config/duplicate";
    const rep: AxiosResponse<TrivialConfigExt> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** DuplicateTrivialPoursuit wraps rawDuplicateTrivialPoursuit and handles the error */
  async DuplicateTrivialPoursuit(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawDuplicateTrivialPoursuit(params);
      this.onSuccessDuplicateTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessDuplicateTrivialPoursuit(
    data: TrivialConfigExt
  ): void;

  protected async rawCheckMissingQuestions(params: CategoriesQuestions) {
    const fullUrl =
      this.baseUrl + "/prof/trivial/config/check-missing-questions";
    const rep: AxiosResponse<CheckMissingQuestionsOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** CheckMissingQuestions wraps rawCheckMissingQuestions and handles the error */
  async CheckMissingQuestions(params: CategoriesQuestions) {
    this.startRequest();
    try {
      const out = await this.rawCheckMissingQuestions(params);
      this.onSuccessCheckMissingQuestions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessCheckMissingQuestions(
    data: CheckMissingQuestionsOut
  ): void;

  protected async rawLaunchSessionTrivialPoursuit(params: LaunchSessionIn) {
    const fullUrl = this.baseUrl + "/trivial/launch_session";
    const rep: AxiosResponse<LaunchSessionOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** LaunchSessionTrivialPoursuit wraps rawLaunchSessionTrivialPoursuit and handles the error */
  async LaunchSessionTrivialPoursuit(params: LaunchSessionIn) {
    this.startRequest();
    try {
      const out = await this.rawLaunchSessionTrivialPoursuit(params);
      this.onSuccessLaunchSessionTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessLaunchSessionTrivialPoursuit(
    data: LaunchSessionOut
  ): void;

  protected async rawStopSessionTrivialPoursuit(params: { id: number }) {
    const fullUrl = this.baseUrl + "/trivial/launch_session";
    const rep: AxiosResponse<any> = await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** StopSessionTrivialPoursuit wraps rawStopSessionTrivialPoursuit and handles the error */
  async StopSessionTrivialPoursuit(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawStopSessionTrivialPoursuit(params);
      this.onSuccessStopSessionTrivialPoursuit(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessStopSessionTrivialPoursuit(data: any): void;

  protected async rawEditorStartSession(params: any) {
    const fullUrl = this.baseUrl + "/prof/editor/api/new";
    const rep: AxiosResponse<StartSessionOut> = await Axios.put(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorStartSession wraps rawEditorStartSession and handles the error */
  async EditorStartSession(params: any) {
    this.startRequest();
    try {
      const out = await this.rawEditorStartSession(params);
      this.onSuccessEditorStartSession(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorStartSession(data: StartSessionOut): void;

  protected async rawEditorGetTags() {
    const fullUrl = this.baseUrl + "/prof/editor/api/tags";
    const rep: AxiosResponse<string[] | null> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorGetTags wraps rawEditorGetTags and handles the error */
  async EditorGetTags() {
    this.startRequest();
    try {
      const out = await this.rawEditorGetTags();
      this.onSuccessEditorGetTags(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorGetTags(data: string[] | null): void;

  protected async rawEditorSearchQuestions(params: ListQuestionsIn) {
    const fullUrl = this.baseUrl + "/prof/editor/api/questions";
    const rep: AxiosResponse<ListQuestionsOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorSearchQuestions wraps rawEditorSearchQuestions and handles the error */
  async EditorSearchQuestions(params: ListQuestionsIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorSearchQuestions(params);
      this.onSuccessEditorSearchQuestions(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSearchQuestions(
    data: ListQuestionsOut
  ): void;

  protected async rawEditorDuplicateQuestion(params: { id: number }) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question-duplicate-one";
    const rep: AxiosResponse<Question> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDuplicateQuestion wraps rawEditorDuplicateQuestion and handles the error */
  async EditorDuplicateQuestion(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDuplicateQuestion(params);
      this.onSuccessEditorDuplicateQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDuplicateQuestion(data: Question): void;

  protected async rawEditorDuplicateQuestionWithDifficulty(params: {
    id: number;
  }) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question-duplicate";
    const rep: AxiosResponse<any> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDuplicateQuestionWithDifficulty wraps rawEditorDuplicateQuestionWithDifficulty and handles the error */
  async EditorDuplicateQuestionWithDifficulty(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDuplicateQuestionWithDifficulty(params);
      this.onSuccessEditorDuplicateQuestionWithDifficulty(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDuplicateQuestionWithDifficulty(
    data: any
  ): void;

  protected async rawEditorCreateQuestion(params: any) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question";
    const rep: AxiosResponse<Question> = await Axios.put(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorCreateQuestion wraps rawEditorCreateQuestion and handles the error */
  async EditorCreateQuestion(params: any) {
    this.startRequest();
    try {
      const out = await this.rawEditorCreateQuestion(params);
      this.onSuccessEditorCreateQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorCreateQuestion(data: Question): void;

  protected async rawEditorGetQuestion(params: { id: number }) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question";
    const rep: AxiosResponse<Question> = await Axios.get(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorGetQuestion wraps rawEditorGetQuestion and handles the error */
  async EditorGetQuestion(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorGetQuestion(params);
      this.onSuccessEditorGetQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorGetQuestion(data: Question): void;

  protected async rawEditorDeleteQuestion(params: { id: number }) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question";
    const rep: AxiosResponse<any> = await Axios.delete(fullUrl, {
      params: { id: String(params["id"]) },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorDeleteQuestion wraps rawEditorDeleteQuestion and handles the error */
  async EditorDeleteQuestion(params: { id: number }) {
    this.startRequest();
    try {
      const out = await this.rawEditorDeleteQuestion(params);
      this.onSuccessEditorDeleteQuestion(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorDeleteQuestion(data: any): void;

  protected async rawEditorSaveAndPreview(params: SaveAndPreviewIn) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question";
    const rep: AxiosResponse<SaveAndPreviewOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorSaveAndPreview wraps rawEditorSaveAndPreview and handles the error */
  async EditorSaveAndPreview(params: SaveAndPreviewIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorSaveAndPreview(params);
      this.onSuccessEditorSaveAndPreview(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorSaveAndPreview(
    data: SaveAndPreviewOut
  ): void;

  protected async rawEditorPausePreview(params: { sessionID: string }) {
    const fullUrl = this.baseUrl + "/prof/editor/api/pause-preview";
    const rep: AxiosResponse<any> = await Axios.get(fullUrl, {
      params: { sessionID: params["sessionID"] },
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorPausePreview wraps rawEditorPausePreview and handles the error */
  async EditorPausePreview(params: { sessionID: string }) {
    this.startRequest();
    try {
      const out = await this.rawEditorPausePreview(params);
      this.onSuccessEditorPausePreview(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorPausePreview(data: any): void;

  protected async rawEditorUpdateTags(params: UpdateTagsIn) {
    const fullUrl = this.baseUrl + "/prof/editor/api/question/tags";
    const rep: AxiosResponse<any> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** EditorUpdateTags wraps rawEditorUpdateTags and handles the error */
  async EditorUpdateTags(params: UpdateTagsIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorUpdateTags(params);
      this.onSuccessEditorUpdateTags(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorUpdateTags(data: any): void;

  protected async rawEditorCheckParameters(params: CheckParametersIn) {
    const fullUrl = this.baseUrl + "/prof/editor/api/check-params";
    const rep: AxiosResponse<CheckParametersOut> = await Axios.post(
      fullUrl,
      params,
      { headers: this.getHeaders() }
    );
    return rep.data;
  }

  /** EditorCheckParameters wraps rawEditorCheckParameters and handles the error */
  async EditorCheckParameters(params: CheckParametersIn) {
    this.startRequest();
    try {
      const out = await this.rawEditorCheckParameters(params);
      this.onSuccessEditorCheckParameters(out);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected abstract onSuccessEditorCheckParameters(
    data: CheckParametersOut
  ): void;
}
