// Code generated by structgen DO NOT EDIT
// github.com/benoitkugler/maths-online/prof/trivial.QuestionCriterion
export type QuestionCriterion = (string[] | null)[] | null;
// github.com/benoitkugler/maths-online/prof/trivial.CategoriesQuestions
export type CategoriesQuestions = QuestionCriterion[];
// github.com/benoitkugler/maths-online/prof/trivial.TrivialConfig
export interface TrivialConfig {
  Id: number;
  Questions: CategoriesQuestions;
  QuestionTimeout: number;
  ShowDecrassage: boolean;
  Public: boolean;
  id_teacher: number;
  Name: string;
}
