// Code generated by structgen DO NOT EDIT
// github.com/benoitkugler/maths-online/trivial-poursuit/game.Success
export type Success = boolean[];
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.gamePlayers
export interface gamePlayers {
  Player: string;
  Successes: Success;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.gameSummary
export interface gameSummary {
  GameID: string;
  CurrentPlayer: string;
  Players: gamePlayers[] | null;
  RoomSize: number;
}
// github.com/benoitkugler/maths-online/prof/trivial-poursuit.teacherSocketData
export interface teacherSocketData {
  Games: gameSummary[] | null;
}
