-- DO NOT EDIT - autogenerated by structgen
CREATE TABLE teacher_questions (
    id_teacher integer NOT NULL,
    id_question integer NOT NULL,
    is_public boolean NOT NULL
);

ALTER TABLE teacher_questions
    ADD FOREIGN KEY (id_teacher) REFERENCES teachers;

ALTER TABLE teacher_questions
    ADD FOREIGN KEY (id_question) REFERENCES questions;

ALTER TABLE teacher_questions
    ADD UNIQUE (id_question);

