package homework

import (
	"math/rand"
	"time"

	"github.com/benoitkugler/maths-online/prof/editor"
	"github.com/benoitkugler/maths-online/prof/teacher"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randIdSheet() IdSheet {
	return IdSheet(randint64())
}

func randNotation() Notation {
	choix := [...]Notation{NoNotation, SuccessNotation}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randSheet() Sheet {
	return Sheet{
		Id:          randIdSheet(),
		IdClassroom: randtea_IdClassroom(),
		Title:       randstring(),
		Notation:    randNotation(),
		Activated:   randbool(),
		Deadline:    randTime(),
	}
}

func randSheetExercice() SheetExercice {
	return SheetExercice{
		IdSheet:    randIdSheet(),
		IdExercice: randedi_IdExercice(),
		Index:      randint(),
	}
}

func randStudentProgression() StudentProgression {
	return StudentProgression{
		IdStudent:     randtea_IdStudent(),
		IdSheet:       randIdSheet(),
		Index:         randint(),
		IdExercice:    randedi_IdExercice(),
		IdProgression: randedi_IdProgression(),
	}
}

func randTime() Time {
	return Time(randtTime())
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randedi_IdExercice() editor.IdExercice {
	return editor.IdExercice(randint64())
}

func randedi_IdProgression() editor.IdProgression {
	return editor.IdProgression(randint64())
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 50)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}

func randtea_IdClassroom() teacher.IdClassroom {
	return teacher.IdClassroom(randint64())
}

func randtea_IdStudent() teacher.IdStudent {
	return teacher.IdStudent(randint64())
}
