// Code generated by structgen. DO NOT EDIT

typedef JSON = Map<String, dynamic>; // alias to shorten JSON convertors

int intFromJson(dynamic json) => json as int;

int intToJson(int item) => item;

String stringFromJson(dynamic json) => json == null ? "" : json as String;

String stringToJson(String item) => item;

// github.com/benoitkugler/maths-online/prof/teacher.StudentHeader
class StudentHeader {
  final int id;
  final String label;

  const StudentHeader(this.id, this.label);

  @override
  String toString() {
    return "StudentHeader($id, $label)";
  }
}

StudentHeader studentHeaderFromJson(dynamic json_) {
  final json = (json_ as JSON);
  return StudentHeader(intFromJson(json['Id']), stringFromJson(json['Label']));
}

JSON studentHeaderToJson(StudentHeader item) {
  return {"Id": intToJson(item.id), "Label": stringToJson(item.label)};
}

List<StudentHeader> listStudentHeaderFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(studentHeaderFromJson).toList();
}

List<dynamic> listStudentHeaderToJson(List<StudentHeader> item) {
  return item.map(studentHeaderToJson).toList();
}

// github.com/benoitkugler/maths-online/prof/teacher.AttachStudentToClassroom2In
class AttachStudentToClassroom2In {
  final String classroomCode;
  final int idStudent;
  final String birthday;

  const AttachStudentToClassroom2In(
      this.classroomCode, this.idStudent, this.birthday);

  @override
  String toString() {
    return "AttachStudentToClassroom2In($classroomCode, $idStudent, $birthday)";
  }
}

AttachStudentToClassroom2In attachStudentToClassroom2InFromJson(dynamic json_) {
  final json = (json_ as JSON);
  return AttachStudentToClassroom2In(stringFromJson(json['ClassroomCode']),
      intFromJson(json['IdStudent']), stringFromJson(json['Birthday']));
}

JSON attachStudentToClassroom2InToJson(AttachStudentToClassroom2In item) {
  return {
    "ClassroomCode": stringToJson(item.classroomCode),
    "IdStudent": intToJson(item.idStudent),
    "Birthday": stringToJson(item.birthday)
  };
}

bool boolFromJson(dynamic json) => json as bool;

bool boolToJson(bool item) => item;

// github.com/benoitkugler/maths-online/prof/teacher.AttachStudentToClassroom2Out
class AttachStudentToClassroom2Out {
  final bool errInvalidBirthday;
  final String idCrypted;

  const AttachStudentToClassroom2Out(this.errInvalidBirthday, this.idCrypted);

  @override
  String toString() {
    return "AttachStudentToClassroom2Out($errInvalidBirthday, $idCrypted)";
  }
}

AttachStudentToClassroom2Out attachStudentToClassroom2OutFromJson(
    dynamic json_) {
  final json = (json_ as JSON);
  return AttachStudentToClassroom2Out(boolFromJson(json['ErrInvalidBirthday']),
      stringFromJson(json['IdCrypted']));
}

JSON attachStudentToClassroom2OutToJson(AttachStudentToClassroom2Out item) {
  return {
    "ErrInvalidBirthday": boolToJson(item.errInvalidBirthday),
    "IdCrypted": stringToJson(item.idCrypted)
  };
}
