package trivial

import (
	"math/rand"

	"github.com/benoitkugler/maths-online/server/src/sql/editor"
	"github.com/benoitkugler/maths-online/server/src/sql/teacher"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randArray5QuestionCriterion() [5]QuestionCriterion {
	var out [5]QuestionCriterion
	for i := range out {
		out[i] = randQuestionCriterion()
	}
	return out
}

func randCategoriesQuestions() CategoriesQuestions {
	return CategoriesQuestions{
		Tags:         randArray5QuestionCriterion(),
		Difficulties: randedi_DifficultyQuery(),
	}
}

func randIdTrivial() IdTrivial {
	return IdTrivial(randint64())
}

func randQuestionCriterion() QuestionCriterion {
	return QuestionCriterion(randSliceSlicestring())
}

func randSliceSlicestring() [][]string {
	l := 40 + rand.Intn(10)
	out := make([][]string, l)
	for i := range out {
		out[i] = randSlicestring()
	}
	return out
}

func randSliceedi_DifficultyTag() []editor.DifficultyTag {
	l := 40 + rand.Intn(10)
	out := make([]editor.DifficultyTag, l)
	for i := range out {
		out[i] = randedi_DifficultyTag()
	}
	return out
}

func randSlicestring() []string {
	l := 40 + rand.Intn(10)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randTrivial() Trivial {
	return Trivial{
		Id:              randIdTrivial(),
		Questions:       randCategoriesQuestions(),
		QuestionTimeout: randint(),
		ShowDecrassage:  randbool(),
		Public:          randbool(),
		IdTeacher:       randtea_IdTeacher(),
		Name:            randstring(),
	}
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randedi_DifficultyQuery() editor.DifficultyQuery {
	return editor.DifficultyQuery(randSliceedi_DifficultyTag())
}

func randedi_DifficultyTag() editor.DifficultyTag {
	choix := [...]editor.DifficultyTag{editor.Diff1, editor.Diff2, editor.Diff3, editor.DiffEmpty}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 50)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtea_IdTeacher() teacher.IdTeacher {
	return teacher.IdTeacher(randint64())
}
