// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.Advance
typedef Advance = List<Rank>;

Advance advanceFromJson(dynamic json) {
  return listRankFromJson(json);
}

dynamic advanceToJson(Advance item) {
  return listRankToJson(item);
}

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.Domain
enum Domain {
  calculMentalI,
  calculMentalII,
  puissances,
  fractions,
  reduction,
  factorisation,
  developpement,
  isolerVariable,
  equations,
  inequations,
  derivation,
  matrices
}

extension _DomainExt on Domain {
  static Domain fromValue(int i) {
    return Domain.values[i];
  }

  int toValue() {
    return index;
  }
}

String domainLabel(Domain v) {
  switch (v) {
    case Domain.calculMentalI:
      return "Calcul mental I";
    case Domain.calculMentalII:
      return "Calcul mental II";
    case Domain.puissances:
      return "Puissances et racines";
    case Domain.fractions:
      return "Fractions";
    case Domain.reduction:
      return "Réduction";
    case Domain.factorisation:
      return "Factorisation";
    case Domain.developpement:
      return "Développement";
    case Domain.isolerVariable:
      return "Isoler une variable";
    case Domain.equations:
      return "Équations";
    case Domain.inequations:
      return "Inéquations";
    case Domain.derivation:
      return "Dérivation";
    case Domain.matrices:
      return "Matrices et systèmes";
  }
}

Domain domainFromJson(dynamic json) => _DomainExt.fromValue(json as int);

dynamic domainToJson(Domain item) => item.toValue();

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.IdBeltquestion
typedef IdBeltquestion = int;

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.Level
enum Level { seconde, premiere, terminale, postBac }

extension _LevelExt on Level {
  static Level fromValue(int i) {
    return Level.values[i];
  }

  int toValue() {
    return index;
  }
}

String levelLabel(Level v) {
  switch (v) {
    case Level.seconde:
      return "Seconde";
    case Level.premiere:
      return "Première";
    case Level.terminale:
      return "Terminale";
    case Level.postBac:
      return "Post-bac";
  }
}

Level levelFromJson(dynamic json) => _LevelExt.fromValue(json as int);

dynamic levelToJson(Level item) => item.toValue();

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.Rank
enum Rank {
  startRank,
  blanche,
  jaune,
  orange,
  verteI,
  verteII,
  bleue,
  violet,
  rouge,
  marron,
  noire
}

extension _RankExt on Rank {
  static Rank fromValue(int i) {
    return Rank.values[i];
  }

  int toValue() {
    return index;
  }
}

String rankLabel(Rank v) {
  switch (v) {
    case Rank.startRank:
      return "Départ";
    case Rank.blanche:
      return "Blanche";
    case Rank.jaune:
      return "Jaune";
    case Rank.orange:
      return "Orange";
    case Rank.verteI:
      return "Verte clair";
    case Rank.verteII:
      return "Verte foncée";
    case Rank.bleue:
      return "Bleue";
    case Rank.violet:
      return "Violette";
    case Rank.rouge:
      return "Rouge";
    case Rank.marron:
      return "Marron";
    case Rank.noire:
      return "Noire";
  }
}

Rank rankFromJson(dynamic json) => _RankExt.fromValue(json as int);

dynamic rankToJson(Rank item) => item.toValue();

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.Stat
class Stat {
  final int success;
  final int failure;

  const Stat(this.success, this.failure);

  @override
  String toString() {
    return "Stat($success, $failure)";
  }
}

Stat statFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return Stat(intFromJson(json['Success']), intFromJson(json['Failure']));
}

Map<String, dynamic> statToJson(Stat item) {
  return {
    "Success": intToJson(item.success),
    "Failure": intToJson(item.failure)
  };
}

// github.com/benoitkugler/maths-online/server/src/sql/ceintures.Stats
typedef Stats = List<List<Stat>>;

Stats statsFromJson(dynamic json) {
  return listListStatFromJson(json);
}

dynamic statsToJson(Stats item) {
  return listListStatToJson(item);
}

List<List<Stat>> listListStatFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(listStatFromJson).toList();
}

List<dynamic> listListStatToJson(List<List<Stat>> item) {
  return item.map(listStatToJson).toList();
}

List<Rank> listRankFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(rankFromJson).toList();
}

List<dynamic> listRankToJson(List<Rank> item) {
  return item.map(rankToJson).toList();
}

List<Stat> listStatFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(statFromJson).toList();
}

List<dynamic> listStatToJson(List<Stat> item) {
  return item.map(statToJson).toList();
}
