// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';
import 'src_maths_questions_client.dart';
import 'src_sql_editor.dart';
import 'src_sql_trivial.dart';
import 'src_tasks.dart';

// github.com/benoitkugler/maths-online/server/src/automatismes.EvaluateAutomatismeIn
class EvaluateAutomatismeIn {
  final IdQuestion id;
  final AnswerP answer;

  const EvaluateAutomatismeIn(this.id, this.answer);

  @override
  String toString() {
    return "EvaluateAutomatismeIn($id, $answer)";
  }
}

EvaluateAutomatismeIn evaluateAutomatismeInFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return EvaluateAutomatismeIn(
    intFromJson(json['Id']),
    answerPFromJson(json['Answer']),
  );
}

Map<String, dynamic> evaluateAutomatismeInToJson(EvaluateAutomatismeIn item) {
  return {"Id": intToJson(item.id), "Answer": answerPToJson(item.answer)};
}

// github.com/benoitkugler/maths-online/server/src/automatismes.GetAutomatismesIn
class GetAutomatismesIn {
  final LevelTag level;
  final String sublevel;

  const GetAutomatismesIn(this.level, this.sublevel);

  @override
  String toString() {
    return "GetAutomatismesIn($level, $sublevel)";
  }
}

GetAutomatismesIn getAutomatismesInFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return GetAutomatismesIn(
    levelTagFromJson(json['Level']),
    stringFromJson(json['Sublevel']),
  );
}

Map<String, dynamic> getAutomatismesInToJson(GetAutomatismesIn item) {
  return {
    "Level": levelTagToJson(item.level),
    "Sublevel": stringToJson(item.sublevel),
  };
}

// github.com/benoitkugler/maths-online/server/src/automatismes.GetAutomatismesOut
class GetAutomatismesOut {
  final List<Trivial> trivials;
  final List<Questiongroup> questions;

  const GetAutomatismesOut(this.trivials, this.questions);

  @override
  String toString() {
    return "GetAutomatismesOut($trivials, $questions)";
  }
}

GetAutomatismesOut getAutomatismesOutFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return GetAutomatismesOut(
    listTrivialFromJson(json['Trivials']),
    listQuestiongroupFromJson(json['Questions']),
  );
}

Map<String, dynamic> getAutomatismesOutToJson(GetAutomatismesOut item) {
  return {
    "Trivials": listTrivialToJson(item.trivials),
    "Questions": listQuestiongroupToJson(item.questions),
  };
}

// github.com/benoitkugler/maths-online/server/src/automatismes.InstantiatedAutomatismeQuestion
class InstantiatedAutomatismeQuestion {
  final IdQuestion id;
  final Question question;
  final Params params;

  const InstantiatedAutomatismeQuestion(this.id, this.question, this.params);

  @override
  String toString() {
    return "InstantiatedAutomatismeQuestion($id, $question, $params)";
  }
}

InstantiatedAutomatismeQuestion instantiatedAutomatismeQuestionFromJson(
  dynamic json_,
) {
  final json = (json_ as Map<String, dynamic>);
  return InstantiatedAutomatismeQuestion(
    intFromJson(json['Id']),
    questionFromJson(json['Question']),
    paramsFromJson(json['Params']),
  );
}

Map<String, dynamic> instantiatedAutomatismeQuestionToJson(
  InstantiatedAutomatismeQuestion item,
) {
  return {
    "Id": intToJson(item.id),
    "Question": questionToJson(item.question),
    "Params": paramsToJson(item.params),
  };
}

List<Questiongroup> listQuestiongroupFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(questiongroupFromJson).toList();
}

List<dynamic> listQuestiongroupToJson(List<Questiongroup> item) {
  return item.map(questiongroupToJson).toList();
}

List<Trivial> listTrivialFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(trivialFromJson).toList();
}

List<dynamic> listTrivialToJson(List<Trivial> item) {
  return item.map(trivialToJson).toList();
}
