// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'src_maths_questions.dart';
import 'src_maths_questions_client.dart';
import 'src_tasks.dart';

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopackEvaluateQuestionIn
class LoopackEvaluateQuestionIn {
  final QuestionPage question;
  final AnswerP answer;

  const LoopackEvaluateQuestionIn(this.question, this.answer);

  @override
  String toString() {
    return "LoopackEvaluateQuestionIn($question, $answer)";
  }
}

LoopackEvaluateQuestionIn loopackEvaluateQuestionInFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopackEvaluateQuestionIn(
      questionPageFromJson(json['Question']), answerPFromJson(json['Answer']));
}

Map<String, dynamic> loopackEvaluateQuestionInToJson(
    LoopackEvaluateQuestionIn item) {
  return {
    "Question": questionPageToJson(item.question),
    "Answer": answerPToJson(item.answer)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackEvaluateQuestionOut
class LoopbackEvaluateQuestionOut {
  final QuestionAnswersOut answers;

  const LoopbackEvaluateQuestionOut(this.answers);

  @override
  String toString() {
    return "LoopbackEvaluateQuestionOut($answers)";
  }
}

LoopbackEvaluateQuestionOut loopbackEvaluateQuestionOutFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopbackEvaluateQuestionOut(
      questionAnswersOutFromJson(json['Answers']));
}

Map<String, dynamic> loopbackEvaluateQuestionOutToJson(
    LoopbackEvaluateQuestionOut item) {
  return {"Answers": questionAnswersOutToJson(item.answers)};
}

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackPaused
class LoopbackPaused implements LoopbackServerEvent {
  const LoopbackPaused();

  @override
  String toString() {
    return "LoopbackPaused()";
  }
}

LoopbackPaused loopbackPausedFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopbackPaused();
}

Map<String, dynamic> loopbackPausedToJson(LoopbackPaused item) {
  return {};
}

/// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackServerEvent
abstract class LoopbackServerEvent {}

LoopbackServerEvent loopbackServerEventFromJson(dynamic json_) {
  final json = json_ as Map<String, dynamic>;
  final kind = json['Kind'] as String;
  final data = json['Data'];
  switch (kind) {
    case "LoopbackPaused":
      return loopbackPausedFromJson(data);
    case "LoopbackShowExercice":
      return loopbackShowExerciceFromJson(data);
    case "LoopbackShowQuestion":
      return loopbackShowQuestionFromJson(data);
    default:
      throw ("unexpected type");
  }
}

Map<String, dynamic> loopbackServerEventToJson(LoopbackServerEvent item) {
  if (item is LoopbackPaused) {
    return {'Kind': "LoopbackPaused", 'Data': loopbackPausedToJson(item)};
  } else if (item is LoopbackShowExercice) {
    return {
      'Kind': "LoopbackShowExercice",
      'Data': loopbackShowExerciceToJson(item)
    };
  } else if (item is LoopbackShowQuestion) {
    return {
      'Kind': "LoopbackShowQuestion",
      'Data': loopbackShowQuestionToJson(item)
    };
  } else {
    throw ("unexpected type");
  }
}

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackShowExercice
class LoopbackShowExercice implements LoopbackServerEvent {
  final InstantiatedWork exercice;
  final ProgressionExt progression;
  final List<QuestionPage> origin;

  const LoopbackShowExercice(this.exercice, this.progression, this.origin);

  @override
  String toString() {
    return "LoopbackShowExercice($exercice, $progression, $origin)";
  }
}

LoopbackShowExercice loopbackShowExerciceFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopbackShowExercice(
      instantiatedWorkFromJson(json['Exercice']),
      progressionExtFromJson(json['Progression']),
      listQuestionPageFromJson(json['Origin']));
}

Map<String, dynamic> loopbackShowExerciceToJson(LoopbackShowExercice item) {
  return {
    "Exercice": instantiatedWorkToJson(item.exercice),
    "Progression": progressionExtToJson(item.progression),
    "Origin": listQuestionPageToJson(item.origin)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackShowQuestion
class LoopbackShowQuestion implements LoopbackServerEvent {
  final Question question;
  final Params params;
  final QuestionPage origin;

  const LoopbackShowQuestion(this.question, this.params, this.origin);

  @override
  String toString() {
    return "LoopbackShowQuestion($question, $params, $origin)";
  }
}

LoopbackShowQuestion loopbackShowQuestionFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopbackShowQuestion(questionFromJson(json['Question']),
      paramsFromJson(json['Params']), questionPageFromJson(json['Origin']));
}

Map<String, dynamic> loopbackShowQuestionToJson(LoopbackShowQuestion item) {
  return {
    "Question": questionToJson(item.question),
    "Params": paramsToJson(item.params),
    "Origin": questionPageToJson(item.origin)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackShowQuestionAnswerIn
class LoopbackShowQuestionAnswerIn {
  final QuestionPage question;
  final Params params;

  const LoopbackShowQuestionAnswerIn(this.question, this.params);

  @override
  String toString() {
    return "LoopbackShowQuestionAnswerIn($question, $params)";
  }
}

LoopbackShowQuestionAnswerIn loopbackShowQuestionAnswerInFromJson(
    dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopbackShowQuestionAnswerIn(
      questionPageFromJson(json['Question']), paramsFromJson(json['Params']));
}

Map<String, dynamic> loopbackShowQuestionAnswerInToJson(
    LoopbackShowQuestionAnswerIn item) {
  return {
    "Question": questionPageToJson(item.question),
    "Params": paramsToJson(item.params)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/editor.LoopbackShowQuestionAnswerOut
class LoopbackShowQuestionAnswerOut {
  final QuestionAnswersIn answers;

  const LoopbackShowQuestionAnswerOut(this.answers);

  @override
  String toString() {
    return "LoopbackShowQuestionAnswerOut($answers)";
  }
}

LoopbackShowQuestionAnswerOut loopbackShowQuestionAnswerOutFromJson(
    dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return LoopbackShowQuestionAnswerOut(
      questionAnswersInFromJson(json['Answers']));
}

Map<String, dynamic> loopbackShowQuestionAnswerOutToJson(
    LoopbackShowQuestionAnswerOut item) {
  return {"Answers": questionAnswersInToJson(item.answers)};
}

List<QuestionPage> listQuestionPageFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(questionPageFromJson).toList();
}

List<dynamic> listQuestionPageToJson(List<QuestionPage> item) {
  return item.map(questionPageToJson).toList();
}
