// Code generated by gomacro/generator/dart. DO NOT EDIT

import 'predefined.dart';
import 'src_sql_teacher.dart';

// github.com/benoitkugler/maths-online/server/src/prof/teacher.AttachStudentToClassroom1Out
typedef AttachStudentToClassroom1Out = List<StudentHeader>;

AttachStudentToClassroom1Out attachStudentToClassroom1OutFromJson(
    dynamic json) {
  return listStudentHeaderFromJson(json);
}

dynamic attachStudentToClassroom1OutToJson(AttachStudentToClassroom1Out item) {
  return listStudentHeaderToJson(item);
}

// github.com/benoitkugler/maths-online/server/src/prof/teacher.AttachStudentToClassroom2In
class AttachStudentToClassroom2In {
  final String classroomCode;
  final IdStudent idStudent;
  final String birthday;

  const AttachStudentToClassroom2In(
      this.classroomCode, this.idStudent, this.birthday);

  @override
  String toString() {
    return "AttachStudentToClassroom2In($classroomCode, $idStudent, $birthday)";
  }
}

AttachStudentToClassroom2In attachStudentToClassroom2InFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return AttachStudentToClassroom2In(stringFromJson(json['ClassroomCode']),
      intFromJson(json['IdStudent']), stringFromJson(json['Birthday']));
}

Map<String, dynamic> attachStudentToClassroom2InToJson(
    AttachStudentToClassroom2In item) {
  return {
    "ClassroomCode": stringToJson(item.classroomCode),
    "IdStudent": intToJson(item.idStudent),
    "Birthday": stringToJson(item.birthday)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/teacher.AttachStudentToClassroom2Out
class AttachStudentToClassroom2Out {
  final bool errInvalidBirthday;
  final bool errAlreadyAttached;
  final String idCrypted;

  const AttachStudentToClassroom2Out(
      this.errInvalidBirthday, this.errAlreadyAttached, this.idCrypted);

  @override
  String toString() {
    return "AttachStudentToClassroom2Out($errInvalidBirthday, $errAlreadyAttached, $idCrypted)";
  }
}

AttachStudentToClassroom2Out attachStudentToClassroom2OutFromJson(
    dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return AttachStudentToClassroom2Out(
      boolFromJson(json['ErrInvalidBirthday']),
      boolFromJson(json['ErrAlreadyAttached']),
      stringFromJson(json['IdCrypted']));
}

Map<String, dynamic> attachStudentToClassroom2OutToJson(
    AttachStudentToClassroom2Out item) {
  return {
    "ErrInvalidBirthday": boolToJson(item.errInvalidBirthday),
    "ErrAlreadyAttached": boolToJson(item.errAlreadyAttached),
    "IdCrypted": stringToJson(item.idCrypted)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/teacher.CheckStudentClassroomOut
class CheckStudentClassroomOut {
  final bool isOK;
  final StudentClassroomHeader meta;

  const CheckStudentClassroomOut(this.isOK, this.meta);

  @override
  String toString() {
    return "CheckStudentClassroomOut($isOK, $meta)";
  }
}

CheckStudentClassroomOut checkStudentClassroomOutFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return CheckStudentClassroomOut(
      boolFromJson(json['IsOK']), studentClassroomHeaderFromJson(json['Meta']));
}

Map<String, dynamic> checkStudentClassroomOutToJson(
    CheckStudentClassroomOut item) {
  return {
    "IsOK": boolToJson(item.isOK),
    "Meta": studentClassroomHeaderToJson(item.meta)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/teacher.StudentClassroomHeader
class StudentClassroomHeader {
  final Student student;
  final String classroomName;
  final String teacherMail;
  final String teacherContactURL;

  const StudentClassroomHeader(this.student, this.classroomName,
      this.teacherMail, this.teacherContactURL);

  @override
  String toString() {
    return "StudentClassroomHeader($student, $classroomName, $teacherMail, $teacherContactURL)";
  }
}

StudentClassroomHeader studentClassroomHeaderFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return StudentClassroomHeader(
      studentFromJson(json['Student']),
      stringFromJson(json['ClassroomName']),
      stringFromJson(json['TeacherMail']),
      stringFromJson(json['TeacherContactURL']));
}

Map<String, dynamic> studentClassroomHeaderToJson(StudentClassroomHeader item) {
  return {
    "Student": studentToJson(item.student),
    "ClassroomName": stringToJson(item.classroomName),
    "TeacherMail": stringToJson(item.teacherMail),
    "TeacherContactURL": stringToJson(item.teacherContactURL)
  };
}

// github.com/benoitkugler/maths-online/server/src/prof/teacher.StudentHeader
class StudentHeader {
  final IdStudent id;
  final String label;

  const StudentHeader(this.id, this.label);

  @override
  String toString() {
    return "StudentHeader($id, $label)";
  }
}

StudentHeader studentHeaderFromJson(dynamic json_) {
  final json = (json_ as Map<String, dynamic>);
  return StudentHeader(intFromJson(json['Id']), stringFromJson(json['Label']));
}

Map<String, dynamic> studentHeaderToJson(StudentHeader item) {
  return {"Id": intToJson(item.id), "Label": stringToJson(item.label)};
}

List<StudentHeader> listStudentHeaderFromJson(dynamic json) {
  if (json == null) {
    return [];
  }
  return (json as List<dynamic>).map(studentHeaderFromJson).toList();
}

List<dynamic> listStudentHeaderToJson(List<StudentHeader> item) {
  return item.map(studentHeaderToJson).toList();
}
