package client

import "encoding/json"

// Code generated by structgen/interfaces. DO NOT EDIT

// AnswerWrapper may be used as replacements for Answer
// when working with JSON
type AnswerWrapper struct {
	Data Answer
}

func (out *AnswerWrapper) UnmarshalJSON(src []byte) error {
	var wr struct {
		Data json.RawMessage
		Kind int
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	switch wr.Kind {
	case 0:
		var data ExpressionAnswer
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 1:
		var data NumberAnswer
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 2:
		var data OrderedListAnswer
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 3:
		var data RadioAnswer
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data

	default:
		panic("exhaustive switch")
	}
	return err
}

func (item AnswerWrapper) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Data interface{}
		Kind int
	}
	var wr wrapper
	switch data := item.Data.(type) {
	case ExpressionAnswer:
		wr = wrapper{Kind: 0, Data: data}
	case NumberAnswer:
		wr = wrapper{Kind: 1, Data: data}
	case OrderedListAnswer:
		wr = wrapper{Kind: 2, Data: data}
	case RadioAnswer:
		wr = wrapper{Kind: 3, Data: data}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}

// BlockWrapper may be used as replacements for Block
// when working with JSON
type BlockWrapper struct {
	Data Block
}

func (out *BlockWrapper) UnmarshalJSON(src []byte) error {
	var wr struct {
		Data json.RawMessage
		Kind int
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	switch wr.Kind {
	case 0:
		var data ExpressionFieldBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 1:
		var data FormulaBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 2:
		var data ListFieldBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 3:
		var data NumberFieldBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 4:
		var data OrderedListFieldBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 5:
		var data RadioFieldBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 6:
		var data SignTableBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 7:
		var data TextBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case 8:
		var data VariationTableBlock
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data

	default:
		panic("exhaustive switch")
	}
	return err
}

func (item BlockWrapper) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Data interface{}
		Kind int
	}
	var wr wrapper
	switch data := item.Data.(type) {
	case ExpressionFieldBlock:
		wr = wrapper{Kind: 0, Data: data}
	case FormulaBlock:
		wr = wrapper{Kind: 1, Data: data}
	case ListFieldBlock:
		wr = wrapper{Kind: 2, Data: data}
	case NumberFieldBlock:
		wr = wrapper{Kind: 3, Data: data}
	case OrderedListFieldBlock:
		wr = wrapper{Kind: 4, Data: data}
	case RadioFieldBlock:
		wr = wrapper{Kind: 5, Data: data}
	case SignTableBlock:
		wr = wrapper{Kind: 6, Data: data}
	case TextBlock:
		wr = wrapper{Kind: 7, Data: data}
	case VariationTableBlock:
		wr = wrapper{Kind: 8, Data: data}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}
