
	-- DO NOT EDIT - autogenerated by structgen 
		   
	
CREATE OR REPLACE FUNCTION f_delfunc (OUT func_dropped int
)
AS $func$
DECLARE
    _sql text;
BEGIN
    SELECT
        count(*)::int,
        'DROP FUNCTION ' || string_agg(oid::regprocedure::text, '; DROP FUNCTION ')
    FROM
        pg_proc
    WHERE
        starts_with (proname, 'structgen_validate_json')
        AND pg_function_is_visible(oid) INTO func_dropped,
        _sql;
    -- only returned if trailing DROPs succeed
    IF func_dropped > 0 THEN
        -- only if function(s) found
        EXECUTE _sql;
    END IF;
END
$func$
LANGUAGE plpgsql;

SELECT
    f_delfunc ();

DROP FUNCTION f_delfunc;


CREATE TABLE exercices (
	id serial PRIMARY KEY,
	title varchar  NOT NULL,
	description varchar  NOT NULL
);

CREATE TABLE formulas (
	Latex varchar  NOT NULL,
	IsInline boolean  NOT NULL
);

CREATE TABLE formula_fields (
	Content varchar  NOT NULL
);

CREATE TABLE list_fields (
	Choices varchar[] 
);

	-- No validation : accept anything
	CREATE OR REPLACE FUNCTION structgen_validate_json_ (data jsonb)
		RETURNS boolean
		AS $f$
	BEGIN
		RETURN TRUE;
	END;
	$f$
	LANGUAGE 'plpgsql'
	IMMUTABLE;

	CREATE OR REPLACE FUNCTION structgen_validate_json_array_ (data jsonb)
		RETURNS boolean
		AS $f$
	BEGIN
		IF jsonb_typeof(data) = 'null' THEN RETURN TRUE; END IF;
		IF jsonb_typeof(data) != 'array' THEN RETURN FALSE; END IF;
		IF jsonb_array_length(data) = 0 THEN RETURN TRUE; END IF; 
		RETURN (SELECT bool_and( structgen_validate_json_(value) )  FROM jsonb_array_elements(data)) 
			;
	END;
	$f$
	LANGUAGE 'plpgsql'
	IMMUTABLE;

CREATE TABLE questions (
	id_exercice integer  NOT NULL,
	content jsonb  CONSTRAINT content_structgen_validate_json_array_ CHECK (structgen_validate_json_array_(content))
);

CREATE TABLE text_blocks (
	Text varchar  NOT NULL
);
ALTER TABLE questions ADD FOREIGN KEY(id_exercice) REFERENCES exercices ON DELETE CASCADE;