package exercice

import "encoding/json"

// Code generated by structgen/interfaces. DO NOT EDIT

func blockUnmarshalJSON(src []byte) (block, error) {
	var wr struct {
		Data json.RawMessage
		Kind int
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return nil, err
	}
	switch wr.Kind {
	case 0:
		var out Formula
		err = json.Unmarshal(wr.Data, &out)
		return out, err
	case 1:
		var out FormulaField
		err = json.Unmarshal(wr.Data, &out)
		return out, err
	case 2:
		var out ListField
		err = json.Unmarshal(wr.Data, &out)
		return out, err
	case 3:
		var out TextBlock
		err = json.Unmarshal(wr.Data, &out)
		return out, err

	default:
		panic("exhaustive switch")
	}
}

func blockMarshalJSON(item block) ([]byte, error) {
	type wrapper struct {
		Data interface{}
		Kind int
	}
	var wr wrapper
	switch item.(type) {
	case Formula:
		wr = wrapper{Kind: 0, Data: item}
	case FormulaField:
		wr = wrapper{Kind: 1, Data: item}
	case ListField:
		wr = wrapper{Kind: 2, Data: item}
	case TextBlock:
		wr = wrapper{Kind: 3, Data: item}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}
