package exercice

// Code generated by structgen. DO NOT EDIT.

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"

	"github.com/lib/pq"
)

func loadJSON(out interface{}, src interface{}) error {
	if src == nil {
		return nil //zero value out
	}
	bs, ok := src.([]byte)
	if !ok {
		return errors.New("not a []byte")
	}
	return json.Unmarshal(bs, out)
}

func dumpJSON(s interface{}) (driver.Value, error) {
	b, err := json.Marshal(s)
	if err != nil {
		return nil, err
	}
	return driver.Value(string(b)), nil
}

// Set is a set of IDs.
type Set map[int64]bool

func NewSet() Set {
	return map[int64]bool{}
}

// NewSetFromSlice returns a set of unique IDs
func NewSetFromSlice(keys []int64) Set {
	out := make(Set, len(keys))
	for _, key := range keys {
		out[key] = true
	}
	return out
}

// Keys return the IDs contained in the set, as a slice.
func (s Set) Keys() []int64 {
	out := make([]int64, 0, len(s))
	for k := range s {
		out = append(out, k)
	}
	return out
}

func (s Set) Has(key int64) bool {
	_, has := s[key]
	return has
}

func (s Set) Add(key int64) {
	s[key] = true
}

type IDs []int64

func (ids IDs) AsSQL() pq.Int64Array {
	return pq.Int64Array(ids)
}

func (ids IDs) AsSet() Set {
	return NewSetFromSlice(ids)
}

// ScanIDs scans the result of a query returning a
// list of IDs.
func ScanIDs(rs *sql.Rows) (IDs, error) {
	defer rs.Close()
	ints := make(IDs, 0, 16)
	var err error
	for rs.Next() {
		var s int64
		if err = rs.Scan(&s); err != nil {
			return nil, err
		}
		ints = append(ints, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return ints, nil
}

type scanner interface {
	Scan(...interface{}) error
}

// DB groups transaction like objects
type DB interface {
	Exec(query string, args ...interface{}) (sql.Result, error)
	Query(query string, args ...interface{}) (*sql.Rows, error)
	QueryRow(query string, args ...interface{}) *sql.Row
	Prepare(query string) (*sql.Stmt, error)
}

func scanOneQuestion(row scanner) (Question, error) {
	var s Question
	err := row.Scan(
		&s.Title,
		&s.Enonce,
		&s.Parameters,
		&s.Id,
	)
	return s, err
}

func ScanQuestion(row *sql.Row) (Question, error) {
	return scanOneQuestion(row)
}

func SelectAllQuestions(tx DB) (Questions, error) {
	rows, err := tx.Query("SELECT * FROM questions")
	if err != nil {
		return nil, err
	}
	return ScanQuestions(rows)
}

// SelectQuestion returns the entry matching id.
func SelectQuestion(tx DB, id int64) (Question, error) {
	row := tx.QueryRow("SELECT * FROM questions WHERE id = $1", id)
	return ScanQuestion(row)
}

// SelectQuestions returns the entry matching the given ids.
func SelectQuestions(tx DB, ids ...int64) (Questions, error) {
	rows, err := tx.Query("SELECT * FROM questions WHERE id = ANY($1)", pq.Int64Array(ids))
	if err != nil {
		return nil, err
	}
	return ScanQuestions(rows)
}

type Questions map[int64]Question

func (m Questions) IDs() IDs {
	out := make(IDs, 0, len(m))
	for i := range m {
		out = append(out, i)
	}
	return out
}

func ScanQuestions(rs *sql.Rows) (Questions, error) {
	var (
		s   Question
		err error
	)
	defer func() {
		errClose := rs.Close()
		if err == nil {
			err = errClose
		}
	}()
	structs := make(Questions, 16)
	for rs.Next() {
		s, err = scanOneQuestion(rs)
		if err != nil {
			return nil, err
		}
		structs[s.Id] = s
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

// Insert Question in the database and returns the item with id filled.
func (item Question) Insert(tx DB) (out Question, err error) {
	row := tx.QueryRow(`INSERT INTO questions (
		title,enonce,parameters
		) VALUES (
		$1,$2,$3
		) RETURNING 
		title,enonce,parameters,id;
		`, item.Title, item.Enonce, item.Parameters)
	return ScanQuestion(row)
}

// Update Question in the database and returns the new version.
func (item Question) Update(tx DB) (out Question, err error) {
	row := tx.QueryRow(`UPDATE questions SET (
		title,enonce,parameters
		) = (
		$2,$3,$4
		) WHERE id = $1 RETURNING 
		title,enonce,parameters,id;
		`, item.Title, item.Enonce, item.Parameters, item.Id)
	return ScanQuestion(row)
}

// Deletes the Question and returns the item
func DeleteQuestionById(tx DB, id int64) (Question, error) {
	row := tx.QueryRow("DELETE FROM questions WHERE id = $1 RETURNING *;", id)
	return ScanQuestion(row)
}

// Deletes the Question in the database and returns the ids.
func DeleteQuestionsByIDs(tx DB, ids ...int64) (IDs, error) {
	rows, err := tx.Query("DELETE FROM questions WHERE id = ANY($1) RETURNING id", pq.Int64Array(ids))
	if err != nil {
		return nil, err
	}
	return ScanIDs(rows)
}

func (s *Enonce) Scan(src interface{}) error  { return loadJSON(s, src) }
func (s Enonce) Value() (driver.Value, error) { return dumpJSON(s) }

func (s *Parameters) Scan(src interface{}) error  { return loadJSON(s, src) }
func (s Parameters) Value() (driver.Value, error) { return dumpJSON(s) }

func scanOneQuestionTag(row scanner) (QuestionTag, error) {
	var s QuestionTag
	err := row.Scan(
		&s.Tag,
		&s.IdQuestion,
	)
	return s, err
}

func ScanQuestionTag(row *sql.Row) (QuestionTag, error) {
	return scanOneQuestionTag(row)
}

func SelectAllQuestionTags(tx DB) (QuestionTags, error) {
	rows, err := tx.Query("SELECT * FROM question_tags")
	if err != nil {
		return nil, err
	}
	return ScanQuestionTags(rows)
}

type QuestionTags []QuestionTag

func ScanQuestionTags(rs *sql.Rows) (QuestionTags, error) {
	var (
		s   QuestionTag
		err error
	)
	defer func() {
		errClose := rs.Close()
		if err == nil {
			err = errClose
		}
	}()
	structs := make(QuestionTags, 0, 16)
	for rs.Next() {
		s, err = scanOneQuestionTag(rs)
		if err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

// Insert the links QuestionTag in the database.
func InsertManyQuestionTags(tx *sql.Tx, items ...QuestionTag) error {
	if len(items) == 0 {
		return nil
	}

	stmt, err := tx.Prepare(pq.CopyIn("question_tags",
		"tag", "id_question",
	))
	if err != nil {
		return err
	}

	for _, item := range items {
		_, err = stmt.Exec(item.Tag, item.IdQuestion)
		if err != nil {
			return err
		}
	}

	if _, err = stmt.Exec(); err != nil {
		return err
	}

	if err = stmt.Close(); err != nil {
		return err
	}
	return nil
}

// Delete the link QuestionTag in the database.
// Only the 'IdQuestion' fields are used.
func (item QuestionTag) Delete(tx DB) error {
	_, err := tx.Exec(`DELETE FROM question_tags WHERE 
	id_question = $1;`, item.IdQuestion)
	return err
}

func SelectQuestionTagsByIdQuestions(tx DB, idQuestions ...int64) (QuestionTags, error) {
	rows, err := tx.Query("SELECT * FROM question_tags WHERE id_question = ANY($1)", pq.Int64Array(idQuestions))
	if err != nil {
		return nil, err
	}
	return ScanQuestionTags(rows)
}

func DeleteQuestionTagsByIdQuestions(tx DB, idQuestions ...int64) (QuestionTags, error) {
	rows, err := tx.Query("DELETE FROM question_tags WHERE id_question = ANY($1) RETURNING *", pq.Int64Array(idQuestions))
	if err != nil {
		return nil, err
	}
	return ScanQuestionTags(rows)
}

// ByIdQuestion returns a map with 'IdQuestion' as keys.
func (items QuestionTags) ByIdQuestion() map[int64]QuestionTags {
	out := make(map[int64]QuestionTags)
	for _, target := range items {
		out[target.IdQuestion] = append(out[target.IdQuestion], target)
	}
	return out
}
