package exercice

import (
	"math/rand"

	"github.com/benoitkugler/maths-online/maths/expression"
	"github.com/benoitkugler/maths-online/maths/repere"
)

// Code generated by structgen. DO NOT EDIT.

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 50)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randrune() rune {
	return rune(rand.Intn(1000000))
}

func randexpressionVariable() expression.Variable {
	return expression.Variable{
		Indice: randstring(),
		Name:   randrune(),
	}
}

func randrandomParameter() randomParameter {
	return randomParameter{
		Expression: randstring(),
		Variable:   randexpressionVariable(),
	}
}

func randSlicerandomParameter() []randomParameter {
	l := rand.Intn(10)
	out := make([]randomParameter, l)
	for i := range out {
		out[i] = randrandomParameter()
	}
	return out
}

func randrandomParameters() randomParameters {
	return randomParameters(randSlicerandomParameter())
}

func randSlicestring() []string {
	l := rand.Intn(10)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randParameters() Parameters {
	return Parameters{
		Variables:  randrandomParameters(),
		Intrinsics: randSlicestring(),
	}
}

func randExercice() Exercice {
	return Exercice{
		Id:          randint64(),
		Title:       randstring(),
		Description: randstring(),
		Parameters:  randParameters(),
	}
}

func randBlock() Block {
	choix := [...]Block{
		randFigureBlock(),
		randFigurePointFieldBlock(),
		randFigureVectorFieldBlock(),
		randFormulaBlock(),
		randFormulaFieldBlock(),
		randFunctionGraphBlock(),
		randFunctionPointsFieldBlock(),
		randFunctionVariationGraphBlock(),
		randNumberFieldBlock(),
		randOrderedListFieldBlock(),
		randRadioFieldBlock(),
		randSignTableBlock(),
		randTableBlock(),
		randTextBlock(),
		randVariationTableBlock(),
		randVariationTableFieldBlock(),
	}
	i := rand.Intn(16)
	return choix[i]
}

func randrepereRandomCoord() repere.RandomCoord {
	return repere.RandomCoord{
		X: randstring(),
		Y: randstring(),
	}
}

func randLabelPos() repere.LabelPos {
	choix := [...]repere.LabelPos{repere.Bottom, repere.BottomLeft, repere.BottomRight, repere.Left, repere.Right, repere.Top, repere.TopLeft, repere.TopRight}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randrepereRandomLabeledPoint() repere.RandomLabeledPoint {
	return repere.RandomLabeledPoint{
		Coord: randrepereRandomCoord(),
		Pos:   randLabelPos(),
	}
}

func randrepereNamedRandomLabeledPoint() repere.NamedRandomLabeledPoint {
	return repere.NamedRandomLabeledPoint{
		Name:  randstring(),
		Point: randrepereRandomLabeledPoint(),
	}
}

func randSlicerepereNamedRandomLabeledPoint() []repere.NamedRandomLabeledPoint {
	l := rand.Intn(10)
	out := make([]repere.NamedRandomLabeledPoint, l)
	for i := range out {
		out[i] = randrepereNamedRandomLabeledPoint()
	}
	return out
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randrepereSegment() repere.Segment {
	return repere.Segment{
		LabelName: randstring(),
		From:      randstring(),
		To:        randstring(),
		LabelPos:  randLabelPos(),
		AsVector:  randbool(),
	}
}

func randSlicerepereSegment() []repere.Segment {
	l := rand.Intn(10)
	out := make([]repere.Segment, l)
	for i := range out {
		out[i] = randrepereSegment()
	}
	return out
}

func randrepereRandomLine() repere.RandomLine {
	return repere.RandomLine{
		Label: randstring(),
		A:     randstring(),
		B:     randstring(),
	}
}

func randSlicerepereRandomLine() []repere.RandomLine {
	l := rand.Intn(10)
	out := make([]repere.RandomLine, l)
	for i := range out {
		out[i] = randrepereRandomLine()
	}
	return out
}

func randrepereRandomDrawings() repere.RandomDrawings {
	return repere.RandomDrawings{
		Points:   randSlicerepereNamedRandomLabeledPoint(),
		Segments: randSlicerepereSegment(),
		Lines:    randSlicerepereRandomLine(),
	}
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randfloat64() float64 {
	return rand.Float64() * float64(rand.Int31())
}

func randrepereCoord() repere.Coord {
	return repere.Coord{
		X: randfloat64(),
		Y: randfloat64(),
	}
}

func randrepereRepereBounds() repere.RepereBounds {
	return repere.RepereBounds{
		Width:  randint(),
		Height: randint(),
		Origin: randrepereCoord(),
	}
}

func randFigureBlock() FigureBlock {
	return FigureBlock{
		Drawings: randrepereRandomDrawings(),
		Bounds:   randrepereRepereBounds(),
		ShowGrid: randbool(),
	}
}

func randCoordExpression() CoordExpression {
	return CoordExpression{
		X: randstring(),
		Y: randstring(),
	}
}

func randFigurePointFieldBlock() FigurePointFieldBlock {
	return FigurePointFieldBlock{
		Answer: randCoordExpression(),
		Figure: randFigureBlock(),
	}
}

func randFigureVectorFieldBlock() FigureVectorFieldBlock {
	return FigureVectorFieldBlock{
		Answer:         randCoordExpression(),
		AnswerOrigin:   randCoordExpression(),
		Figure:         randFigureBlock(),
		MustHaveOrigin: randbool(),
	}
}

func randInterpolated() Interpolated {
	return Interpolated(randstring())
}

func randFormulaBlock() FormulaBlock {
	return FormulaBlock{
		Parts: randInterpolated(),
	}
}

func randTextKind() TextKind {
	choix := [...]TextKind{Expression, StaticMath, Text}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randTextPart() TextPart {
	return TextPart{
		Content: randstring(),
		Kind:    randTextKind(),
	}
}

func randComparisonLevel() expression.ComparisonLevel {
	choix := [...]expression.ComparisonLevel{expression.ExpandedSubstitutions, expression.SimpleSubstitutions, expression.Strict}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randFormulaFieldBlock() FormulaFieldBlock {
	return FormulaFieldBlock{
		Expression:      randstring(),
		Label:           randTextPart(),
		ComparisonLevel: randComparisonLevel(),
	}
}

func randArray2float64() [2]float64 {
	var out [2]float64
	for i := range out {
		out[i] = randfloat64()
	}
	return out
}

func randFunctionGraphBlock() FunctionGraphBlock {
	return FunctionGraphBlock{
		Function: randstring(),
		Label:    randstring(),
		Variable: randexpressionVariable(),
		Range:    randArray2float64(),
	}
}

func randSliceint() []int {
	l := rand.Intn(10)
	out := make([]int, l)
	for i := range out {
		out[i] = randint()
	}
	return out
}

func randFunctionPointsFieldBlock() FunctionPointsFieldBlock {
	return FunctionPointsFieldBlock{
		Function: randstring(),
		Label:    randstring(),
		Variable: randexpressionVariable(),
		XGrid:    randSliceint(),
	}
}

func randFunctionVariationGraphBlock() FunctionVariationGraphBlock {
	return FunctionVariationGraphBlock{
		Xs:  randSlicestring(),
		Fxs: randSlicestring(),
	}
}

func randNumberFieldBlock() NumberFieldBlock {
	return NumberFieldBlock{
		Expression: randstring(),
	}
}

func randSliceTextPart() []TextPart {
	l := rand.Intn(10)
	out := make([]TextPart, l)
	for i := range out {
		out[i] = randTextPart()
	}
	return out
}

func randOrderedListFieldBlock() OrderedListFieldBlock {
	return OrderedListFieldBlock{
		Label:               randstring(),
		Answer:              randSliceTextPart(),
		AdditionalProposals: randSliceTextPart(),
	}
}

func randSliceInterpolated() []Interpolated {
	l := rand.Intn(10)
	out := make([]Interpolated, l)
	for i := range out {
		out[i] = randInterpolated()
	}
	return out
}

func randRadioFieldBlock() RadioFieldBlock {
	return RadioFieldBlock{
		Answer:     randstring(),
		Proposals:  randSliceInterpolated(),
		AsDropDown: randbool(),
	}
}

func randSignSymbol() SignSymbol {
	choix := [...]SignSymbol{ForbiddenValue, Nothing, Zero}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randSliceSignSymbol() []SignSymbol {
	l := rand.Intn(10)
	out := make([]SignSymbol, l)
	for i := range out {
		out[i] = randSignSymbol()
	}
	return out
}

func randSlicebool() []bool {
	l := rand.Intn(10)
	out := make([]bool, l)
	for i := range out {
		out[i] = randbool()
	}
	return out
}

func randSignTableBlock() SignTableBlock {
	return SignTableBlock{
		Xs:        randSliceInterpolated(),
		FxSymbols: randSliceSignSymbol(),
		Signs:     randSlicebool(),
	}
}

func randSliceSliceTextPart() [][]TextPart {
	l := rand.Intn(10)
	out := make([][]TextPart, l)
	for i := range out {
		out[i] = randSliceTextPart()
	}
	return out
}

func randTableBlock() TableBlock {
	return TableBlock{
		HorizontalHeaders: randSliceTextPart(),
		VerticalHeaders:   randSliceTextPart(),
		Values:            randSliceSliceTextPart(),
	}
}

func randTextBlock() TextBlock {
	return TextBlock{
		Parts:  randInterpolated(),
		IsHint: randbool(),
	}
}

func randVariationTableBlock() VariationTableBlock {
	return VariationTableBlock{
		Xs:  randSlicestring(),
		Fxs: randSlicestring(),
	}
}

func randVariationTableFieldBlock() VariationTableFieldBlock {
	return VariationTableFieldBlock{
		Answer: randVariationTableBlock(),
	}
}

func randSliceBlock() []Block {
	l := rand.Intn(10)
	out := make([]Block, l)
	for i := range out {
		out[i] = randBlock()
	}
	return out
}

func randEnonce() Enonce {
	return Enonce(randSliceBlock())
}

func randQuestion() Question {
	return Question{
		Title:      randstring(),
		Enonce:     randEnonce(),
		Parameters: randParameters(),
	}
}
