package exercice

import "math/rand"

// Code generated by structgen. DO NOT EDIT.

func randBlock() Block {
	choix := [...]Block{
		randFormulaBlock(),
		randFormulaField(),
		randListField(),
		randNumberField(),
		randSignTableBlock(),
		randTextBlock(),
		randVariationTableBlock(),
	}
	i := rand.Intn(7)
	return choix[i]
}

func randSliceBlock() []Block {
	l := rand.Intn(10)
	out := make([]Block, l)
	for i := range out {
		out[i] = randBlock()
	}
	return out
}

func randEnonce() Enonce {
	return Enonce(randSliceBlock())
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 50)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randrune() rune {
	return rune(rand.Intn(1000000))
}

func randrandomParameter() randomParameter {
	return randomParameter{
		Expression: randstring(),
		Variable:   randrune(),
	}
}

func randSlicerandomParameter() []randomParameter {
	l := rand.Intn(10)
	out := make([]randomParameter, l)
	for i := range out {
		out[i] = randrandomParameter()
	}
	return out
}

func randrandomParameters() randomParameters {
	return randomParameters(randSlicerandomParameter())
}

func randExercice() Exercice {
	return Exercice{
		Id:               randint64(),
		Title:            randstring(),
		Description:      randstring(),
		RandomParameters: randrandomParameters(),
	}
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randFormulaPart() FormulaPart {
	return FormulaPart{
		Content:      randstring(),
		IsExpression: randbool(),
	}
}

func randSliceFormulaPart() []FormulaPart {
	l := rand.Intn(10)
	out := make([]FormulaPart, l)
	for i := range out {
		out[i] = randFormulaPart()
	}
	return out
}

func randFormulaContent() FormulaContent {
	return FormulaContent(randSliceFormulaPart())
}

func randFormulaBlock() FormulaBlock {
	return FormulaBlock{
		Parts: randFormulaContent(),
	}
}

func randFormulaField() FormulaField {
	return FormulaField{
		Expression: randstring(),
	}
}

func randSlicestring() []string {
	l := rand.Intn(10)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randListField() ListField {
	return ListField{
		Choices: randSlicestring(),
	}
}

func randNumberField() NumberField {
	return NumberField{
		Expression: randstring(),
	}
}

func randQuestion() Question {
	return Question{
		IdExercice: randint64(),
		Title:      randstring(),
		Enonce:     randEnonce(),
	}
}

func randSignSymbol() SignSymbol {
	choix := [...]SignSymbol{ForbiddenValue, Nothing, Zero}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randSliceSignSymbol() []SignSymbol {
	l := rand.Intn(10)
	out := make([]SignSymbol, l)
	for i := range out {
		out[i] = randSignSymbol()
	}
	return out
}

func randSlicebool() []bool {
	l := rand.Intn(10)
	out := make([]bool, l)
	for i := range out {
		out[i] = randbool()
	}
	return out
}

func randSignTableBlock() SignTableBlock {
	return SignTableBlock{
		Xs:        randFormulaContent(),
		FxSymbols: randSliceSignSymbol(),
		Signs:     randSlicebool(),
	}
}

func randTextBlock() TextBlock {
	return TextBlock{
		Parts:  randstring(),
		IsHint: randbool(),
	}
}

func randVariationTableBlock() VariationTableBlock {
	return VariationTableBlock{
		Xs:  randSlicestring(),
		Fxs: randSlicestring(),
	}
}
